### ISSUE TITLE
Show recent changes in event / person tab

### ISSUE THREAD

**Issue by Unicorn-rzl** [frab/frab#142]
It would be really good if conference organizers could see whether a speaker is using Frab at all. Therefore a list of recent changes per event / person (on that page) would be nice. It would be sufficient to see whether there is any change at all, it is not that important to have wiki-like diffs.

**Comment by eladeyal-intel** [comment]
@erdgeist added #628 which adds event history tab. 

I propose this ticket should be closed.

![image](https://user-images.githubusercontent.com/20379005/69482730-c92e7580-0e27-11ea-8444-1c81c95a57e9.png)
