### ISSUE TITLE
Don't prefill the "availability" page / remind speaker to fix missing information

### ISSUE THREAD

**Issue by Unicorn-rzl** [frab/frab#143]
We noticed, that many speakers do not "save" their availability. We believe that this is due to the fact that the speaker do not know that they have to click the "save availability" button at least once.

A speaker has to set its availability. This is done on the availability page. How ever, besides a really small text stating sth. like  "you haven't set your availability, please submit this form" there is no indication, that the prefilled time bars are not really representing the current state. On first (and second) glance, the availability looks perfectly fine. (see picture)
![demonstration](https://cloud.githubusercontent.com/assets/607432/4115830/7d8badea-327d-11e4-97e2-52731b626a91.png)

I would suggest, that those bars are either not filled at all, or that the speaker gets a really big overlay/box/whatever after log in, reminding him to set AND safe its availability.

**Comment by meisterluk** [comment]
@manno I think your bugfix fixes the wrong issue. @Unicorn-rzl showed the availability in the admin interface, but the issue is in the speaker interface (I think so and I think @Unicorn-rzl agrees).

We also experienced this issue just now that speakers do not fill out their availability, because the bars are prefilled and it looks like "filled and saved". One possible fix was suggested by @Unicorn-rzl already. A flash message in the speaker interface like

> you haven't set your availability, please submit this form

(BTW, I think the flash in admin interface is helpful though)

**Comment by fatalmind** [comment]
@manno @meisterluk Another option would be to preselect "no time available" as opposed to "every time available" — that would definitively prompt users to adjust the slides and click save.

**Comment by manno** [comment]
@meisterluk Flash should appear in the speakers interface, is this not working: https://github.com/frab/frab/blob/142b63dfeb1ad1e59b89ee42f8a7bc993adc545f/app/controllers/cfp/people_controller.rb#L11

I also like the idea of filling 'no availabilities', but conferences may want to discern between 'not edited at all', 'is not available or failed to understand sliders'?

**Comment by meisterluk** [comment]
@fatalmind LGTM. I am open to any of these fixes.

@manno I don't see any flash in the speakers interface:
![frab-availability](https://user-images.githubusercontent.com/358358/36150419-f28fcc34-10c3-11e8-90fb-d2ccf424eb8a.png)
This is the speakers interface after creating a new account and going to the "Edit availability" page.

`cat frab/tmp/index/production/event/version` shows version "0.6.8". Not sure this is the proper approach to get the current FRAB version (why is it so difficult to find?).

**Comment by manno** [comment]
frab doesn't have a real version. It's mostly SHA hashes from git. The [releases](https://github.com/frab/frab/releases) are mostly done for the changelog.

**Comment by meisterluk** [comment]
@manno I see. Our current version is `d64f96423d0dae7ccb871b89fce457b067a01820` (Thu Mar 19 14:53:13 2015) in this case.
