### ISSUE TITLE
Massmailing to speakers of a certain conference

### ISSUE THREAD

**Issue by herrurbach** [frab/frab#149]
It would be great if there were a possibility to mail to all speakers of a confirmed event by just hitting one button. 

It would be even more great if this would send via the chosen ticket system but a "normal" email would be good as well.

Bonus, if there would be a note at the speaker that he*seh recieved the email.

**Comment by zonque** [comment]
A minimal version of this is now implemented and pending in PR #181. I'd appreciate testing and feedback.

**Comment by erdgeist** [comment]
A new approach has been implemented in #268.
