### ISSUE TITLE
Logo- und Attachments des Events im schedule.xml

### ISSUE THREAD

**Issue by MaZderMind** [frab/frab#157]
Derzeit sind weder das Talk-Logo- noch die URLs zu den vom Referenten hochgeladenen Attachments im schedule.xml enthalten. Das ist IMO ein Bug und sollte gefixt werden.

Dadurch könnten diese Files auch von der Media-API geladen und auf media.ccc.de angeboten werden.

**Comment by saerdnaer** [comment]
@manno Denkst du es ist vor dem 32C3 noch möglich diesen Feature-Request umzusetzen?

**Comment by saerdnaer** [comment]
@zonque Falls du Zeit hast kannst du dich diesem Issue ja mal annehmen. Siehe auch https://github.com/voc/schedule/issues/9

**Comment by zonque** [comment]
Ich gucke die Tage mal rein. Hatte etliche PRs pending, die aber alle nicht mehr applien. Wenn ich mich wieder reingefuchst habe, schaue ich mir das mal an.

**Comment by manno** [comment]
Glaube das ist in https://github.com/frab/frab/commit/52a3d25f1f991530e3f68a0125245dacf3332fe1 eingebaut.

**Comment by zonque** [comment]
Um so besser :) Habe jetzt alle meine pending PRs in frab nochmal rebased und hoffe auf Feedback. Ich habe auch noch andere features lokal, aber die submitte ich erst danach.

**Comment by saerdnaer** [comment]
Man beachte https://github.com/frab/frab/commit/52a3d25f1f991530e3f68a0125245dacf3332fe1#commitcomment-14942014

**Comment by saerdnaer** [comment]
@manno Kannst du das noch fixen, damit es konsistent ist?

**Comment by manno** [comment]
@saerdnaer Ich hab die Zeile schon geändert, aber hatte nicht gepusht. Vor dem Wochenende kann ich eh nicht neu deployen, zu viele Änderungen und ich habe keine Zeit zum bugfixen.
