### ISSUE TITLE
On clean installation: "ActiveRecord::StatementInvalid (Could not find table 'sessions')"

### ISSUE THREAD

**Issue by alvarezp** [frab/frab#173]
Hi. I just tried a clean installation and got this:

```
ActiveRecord::StatementInvalid (Could not find table 'sessions'):
  activerecord (3.2.21) lib/active_record/connection_adapters/sqlite_adapter.rb:472:in `table_structure'
  activerecord (3.2.21) lib/active_record/connection_adapters/sqlite_adapter.rb:346:in `columns'
  activerecord (3.2.21) lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
  activerecord (3.2.21) lib/active_record/model_schema.rb:229:in `yield'
```

**Comment by alvarezp** [comment]
The instructions I followed were the "Installing" section from README.md. I used `rails serve -e production` to test the server.

**Comment by zonque** [comment]
This looks like you didn't set up the databases.

When deploying production environments, you need to run the `rake` tasks mentioned in the documentation (such as `db:setup`) with `RAILS_ENV=production` appended. By default, rake will use the development env.

I guess that should be explained in the README.
