### ISSUE TITLE
Remove recording license and 'do not record' from cfp forms

### ISSUE THREAD

**Issue by manno** [frab/frab#176]
Both fields should be writable by the events crew only. Putting these fields into the event submission form often collides with the information given in the actual call for participation text.

**Comment by sebix** [comment]
I agree that the license should be not choosable, so no writeable field. Otherwise the submitters want licences like GPL which are not practical for processing and publishing the videos.

Why should the submitters not be able to opt out for recording?

**Comment by manno** [comment]
The conference CFP normally specifies how recordings are handled. Currently the field gets locked after the event is accepted. In the past speakers changed the value an hour before their talk and the video recording crew wasn't informed in time. Any change really should go through the events coordinator/the conference crew.

**Comment by sebix** [comment]
Ah, great. Locking the field for the submitter when the event is accepted is indeed a very good idea, thanks :)

**Comment by manno** [comment]
merged
