### ISSUE TITLE
Search is non-deterministic

### ISSUE THREAD

**Issue by saerdnaer** [frab/frab#178]
Steps to reproduce
* login to frab.cccv.de
* open https://frab.cccv.de/en/camp2015/events?term=badge
* 1 result: save title to brain
* reload page
* again 1 result, but other title -> WTF?
* reload page
* lists the first result again
* reload page
* lists the second result
* goto step 6 and repeat as  long as you want

Expected behavior:
* 2 results, content should be the same after reload

**Comment by manno** [comment]
Since this only happens with the act_as_indexed search this bug has likely been reported as issue #107 
The alternating results happen because only one server has a corrupted index.

Applying #171 should fix this.
