### ISSUE TITLE
English translation files incomplete for use as reference for tranlsation

### ISSUE THREAD

**Issue by alvarezp** [frab/frab#185]
`config/locales/*en.yml` files do not contain all the necessary strings to fully translate Frab. For example, de.yml contains `date.formats.default`.

Thus, translation attempts are unsuccessful because of this. Additionally, the lack of `date.formats.default` crashes the program:

```
ActionView::Template::Error (translation missing: es.date.formats.default):
    40:         %td= event.event_type
    41:         - if can? :crud, Event
    42:           %td= event.state
    43:         %td= l(event.created_at.to_date)
    44:         %td.buttons
    45:           = action_button "small", 'Show', event
    46:           - if can? :crud, event
  app/views/events/_table.html.haml:43:in `block in _app_views_events__table_html_haml___136401978_83631850'
  app/views/events/_table.html.haml:25:in `each'
  app/views/events/_table.html.haml:25:in `_app_views_events__table_html_haml___136401978_83631850'
  app/views/people/show.html.haml:95:in `_app_views_people_show_html_haml___302624183_73539970'
  app/controllers/people_controller.rb:49:in `show'
```

**Comment by mtancoigne** [comment]
I totally agree with the current state of the translations:
  - Hardcoded strings in controllers and views
  - Devise views not overriden, so not translated

Would you be interested by a complete review of this, followed by a PR ?
I started to re-translate everything to french for a project, and i think that strings may be reordered in the yml files too.

What do you think ?

**Comment by manno** [comment]
Huge updates to translations. closing this.
