### ISSUE TITLE
Set all accepted talks to public

### ISSUE THREAD

**Issue by ScottyTM** [frab/frab#190]
I would like to have a button to set all accepted talks to public.

**Comment by sebix** [comment]
Yes, the handling of switching events to public could be improved. We usually add the public flag for all accepted events via a database query.

**Comment by erdgeist** [comment]
Any idea where that should go?

Maybe the tab "mail templates" should become something like "conference admin", where you can "manage conference state transitions" and optionally manipulate a whole list of events in a batch.

**Comment by manno** [comment]
Since the default event state is now 'public' I'm closing this issue.
