### ISSUE TITLE
Registration confirmation mail not delivered for https://frab.cccv.de

### ISSUE THREAD

**Issue by shahn** [frab/frab#202]
Apologies if this is the wrong place to report an apparent configuration issue for cccv, but it seems that the from address used on the https://frab.cccv.de instance is invalid, meaning that some mail servers (for example the ones handling mail to torproject.org and debian.org) will reject the message. I was advised that this might be the best place to reach the people who run the frob instance for cccv infrastructure, please close as invalid/advise otherwise.

Thanks!

**Comment by manno** [comment]
Hi, I changed the from to the frab-team address, should work now. But I think your mail server config is broken ;)
