### ISSUE TITLE
feature request: export speaker profile

### ISSUE THREAD

**Issue by stapelberg** [frab/frab#206]
Each conference that I attend has their own frab instance. Hence, every time, I need to re-enter my speaker profile. It’d be great if I could just download the speaker profile from frab and re-upload it to the next conference.

What do you think?

**Comment by saerdnaer** [comment]
I think you can reuse the methods used to generate the speakers.json, for 32C3 e.g. https://events.ccc.de/congress/2015/Fahrplan/speakers.json

Can you provide a pull request?

**Comment by stapelberg** [comment]
I’m a bit pressed on time these days. I’ll put it on my TODO list, but in case anyone wants to step in before I get around to it, feel free to do so.

**Comment by manno** [comment]
Implementing this in #341
