### ISSUE TITLE
RT support broken?

### ISSUE THREAD

**Issue by manno** [frab/frab#209]
According to FrOScon request tracker support is broken.

**Comment by zonque** [comment]
I just played around with it and it worked fine, also after my rework. What *is* broken, however, is OTRS support. I didn't debug this further but just made sure the request look the same before and after the rework.

What's the exact problem they reported?

**Comment by derchrisuk** [comment]
Sorry, just seen this after I opened #252

**Comment by manno** [comment]
I'm confused. Should I merge https://github.com/frab/frab/pull/242 ?
Is RT working? Why is OTRS broken, did they drop the [old API](https://github.com/frab/frab/issues/111)?

**Comment by erdgeist** [comment]
Well, I'd love to see proper RT integration. Other new features for 33C3 are stalling ;)

**Comment by zonque** [comment]
What exactly isn't working, and was it ever working? Did my rework break the support?
