### ISSUE TITLE
env production, Routing Error at login 

### ISSUE THREAD

**Issue by francrodriguez** [frab/frab#233]
**In environtment production, there is an error after login:**

`I, [2016-05-19T10:12:15.047804 #3040]  INFO -- : Started GET "/favicon.ico" for 194.158.78.246 at 2016-05-19 10:12:15 -0400
I, [2016-05-19T10:12:15.049806 #3040]  INFO -- : Processing by HomeController#index as 
I, [2016-05-19T10:12:15.050097 #3040]  INFO -- :   Parameters: {"conference_acronym"=>"favicon"}
D, [2016-05-19T10:12:15.051164 #3040] DEBUG -- :   Conference Load (0.3ms)  SELECT  "conferences".* FROM "conferences" WHERE "conferences"."acronym" = ? LIMIT 1  [["acronym", "favicon"]]
I, [2016-05-19T10:12:15.051828 #3040]  INFO -- : Completed 404 Not Found in 1ms (ActiveRecord: 0.3ms)
F, [2016-05-19T10:12:15.053334 #3040] FATAL -- : 
ActionController::RoutingError (Not found):
  app/controllers/application_controller.rb:42:in load_conference`

**I comment in config/environments/production.rb this line:**
`# config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?`

**It seems that the routing error is fixed but I can't login with admin@example.org.
Log:**
`, [2016-05-19T10:25:38.313196 #3285]  INFO -- : Started GET "/en/session/new" for 194.158.78.246 at 2016-05-19 10:25:38 -0400
I, [2016-05-19T10:25:38.531350 #3285]  INFO -- : Processing by SessionsController#new as HTML
I, [2016-05-19T10:25:38.531553 #3285]  INFO -- :   Parameters: {"locale"=>"en"}
D, [2016-05-19T10:25:38.565607 #3285] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM "conferences"
I, [2016-05-19T10:25:38.853563 #3285]  INFO -- :   Rendered shared/_flash.html.haml (2.9ms)
I, [2016-05-19T10:25:38.870247 #3285]  INFO -- :   Rendered sessions/new.html.haml within layouts/team_signup (28.4ms)
I, [2016-05-19T10:25:38.879257 #3285]  INFO -- : Completed 200 OK in 347ms (Views: 44.5ms | ActiveRecord: 5.4ms)
I, [2016-05-19T10:25:44.683467 #3285]  INFO -- : Started POST "/en/session" for 194.158.78.246 at 2016-05-19 10:25:44 -0400
I, [2016-05-19T10:25:44.685786 #3285]  INFO -- : Processing by SessionsController#create as HTML
I, [2016-05-19T10:25:44.685929 #3285]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Bhtd7sl/aFiUCz+x1QcSL8RQACUyXLFyCtcMtdrCQedEzgVdfECleiGZfZMKn+t0cqMEIUUPRbq50grOzDwIOg==", "user"=>{"email"=>"admin@example.org", "password"=>"[FILTERED]", "remember_me"=>"0"}, "button"=>"", "locale"=>"en"}
D, [2016-05-19T10:25:44.687954 #3285] DEBUG -- :    (0.3ms)  SELECT COUNT(*) FROM "conferences"
W, [2016-05-19T10:25:44.688595 #3285]  WARN -- : Can't verify CSRF token authenticity
D, [2016-05-19T10:25:44.699117 #3285] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT 1  [["email", "admin@example.org"]]
D, [2016-05-19T10:25:44.704679 #3285] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE ("users"."confirmed_at" IS NOT NULL) AND "users"."email" = ? LIMIT 1  [["email", "admin@example.org"]]
D, [2016-05-19T10:25:44.848919 #3285] DEBUG -- :    (0.2ms)  begin transaction
D, [2016-05-19T10:25:44.863397 #3285] DEBUG -- :   Person Load (0.4ms)  SELECT  "people".* FROM "people" WHERE "people"."user_id" = ? LIMIT 1  [["user_id", 1]]
D, [2016-05-19T10:25:44.898428 #3285] DEBUG -- :   User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE (LOWER("users"."email") = LOWER('admin@example.org') AND "users"."id" != 1) LIMIT 1
D, [2016-05-19T10:25:44.912138 #3285] DEBUG -- :   ConferenceUser Load (0.3ms)  SELECT "conference_users".* FROM "conference_users" WHERE "conference_users"."user_id" = ?  [["user_id", 1]]
D, [2016-05-19T10:25:44.915874 #3285] DEBUG -- :   SQL (0.4ms)  UPDATE "users" SET "last_sign_in_at" = ?, "sign_in_count" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["last_sign_in_at", "2016-05-19 14:25:44.848221"], ["sign_in_count", 15], ["updated_at", "2016-05-19 14:25:44.913100"], ["id", 1]]
D, [2016-05-19T10:25:44.920753 #3285] DEBUG -- :    (3.7ms)  commit transaction
D, [2016-05-19T10:25:44.922734 #3285] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
I, [2016-05-19T10:25:44.924449 #3285]  INFO -- : Redirected to http://frab.francrodriguez.com:3000/?locale=en
I, [2016-05-19T10:25:44.924848 #3285]  INFO -- : Completed 302 Found in 239ms (ActiveRecord: 7.9ms)
I, [2016-05-19T10:25:45.484288 #3285]  INFO -- : Started GET "/?locale=en" for 194.158.78.246 at 2016-05-19 10:25:45 -0400
I, [2016-05-19T10:25:45.490716 #3285]  INFO -- : Processing by HomeController#index as HTML
I, [2016-05-19T10:25:45.490859 #3285]  INFO -- :   Parameters: {"locale"=>"en"}
D, [2016-05-19T10:25:45.493924 #3285] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM "conferences"
I, [2016-05-19T10:25:45.495131 #3285]  INFO -- : Redirected to http://frab.francrodriguez.com:3000/en/session/new
I, [2016-05-19T10:25:45.495439 #3285]  INFO -- : Filter chain halted as :authenticate_user! rendered or redirected
I, [2016-05-19T10:25:45.495763 #3285]  INFO -- : Completed 302 Found in 5ms (ActiveRecord: 0.4ms)
I, [2016-05-19T10:25:46.054845 #3285]  INFO -- : Started GET "/en/session/new" for 194.158.78.246 at 2016-05-19 10:25:46 -0400
I, [2016-05-19T10:25:46.057552 #3285]  INFO -- : Processing by SessionsController#new as HTML
I, [2016-05-19T10:25:46.057720 #3285]  INFO -- :   Parameters: {"locale"=>"en"}
D, [2016-05-19T10:25:46.060844 #3285] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM "conferences"
I, [2016-05-19T10:25:46.065078 #3285]  INFO -- :   Rendered shared/_flash.html.haml (0.3ms)
I, [2016-05-19T10:25:46.082630 #3285]  INFO -- :   Rendered sessions/new.html.haml within layouts/team_signup (18.8ms)
I, [2016-05-19T10:25:46.084634 #3285]  INFO -- : Completed 200 OK in 27ms (Views: 21.9ms | ActiveRecord: 0.5ms)`

**I inspect the database production.sqlite3 and the access is registered:**
`1|admin@example.org|$2a$10$O/Fy3xmmIOuNSlxg76BOTOFMKWWNX16z44qVQ7.RfhGQylX7uElIO||||14||2016-05-19 14:10:14.618871||||2016-05-19 08:15:03.171670||2016-05-19 08:15:03.207202|2016-05-19 14:10:14.664151|admin||`

**In development environment works fine.**

**Comment by manno** [comment]
These are two separate issues.

**favicon.ico interpreted as a conference acronym**
Your production setup is incomplete. If you have no webserver serving your static assets like `favicon.ico`, you need to tell Rails to serve static assets. You can do this with frab by setting `RAILS_SERVE_STATIC_FILES=1`, for example in `.env.production.  

**log in not possible**
This is probably due to missing SSL. frab is not meant to be used via http in production mode.
You can change this behavior in `config/initializers/session_store.rb`, by setting the `secure` cookie flag to `false`.

Both "features", configuring static assets and requiring SSL in production, maybe should be documented in our README.
