### ISSUE TITLE
Feature Request: Adapt PDF schedule export and/or add SVG Export

### ISSUE THREAD

**Issue by bernd-s** [frab/frab#235]
Hi,

I am using the schedule export for the creation of the FrOSCon Programmheft. We print this magazine in A5 Format. Whilst the Export allows us to create full pages in format A5, it currently does not allow to create PDFs which fit on a half page. 
It would be nice either to have the possibility to create export files which have an adaptable page width, or alternatively allow to add an(many) empty dummy column(s) to fill the page in order to have the room you want to see only on half of the page without directly adjacent next rooms.
Another alternative would be to add an SVG export, so that I can scale this as i like.

Hopefully you understood this request. If not feel free to ask. See the attached file as an example where the issue for us is.

regards
Bernd

<img width="505" alt="programmheft" src="https://cloud.githubusercontent.com/assets/7986181/15643846/ccc6279c-264f-11e6-8a00-4c95bc4cb64b.png">

**Comment by manno** [comment]
I believe this works now, you might test it with FrOSCon 2015.

Still, the header is broken and there is the text 'Prof. Dr. Margit Geißler' is in a single line box?

**Comment by bernd-s** [comment]
Hi manno,

it works now. But the problem with the single line box still exists. This always happens if sessions are to short, and thus have not enough space on the grid. Should we create a new Issue for this?
This one I would mark as Solved.

Thanks
Bernd

**Comment by manno** [comment]
Right, changing the layout calculations should be in another ticket.
