### ISSUE TITLE
Add person to event

### ISSUE THREAD

**Issue by herrurbach** [frab/frab#236]
is pain. 

the moment I can choose a person I get a dropdown list with all _public_ names. I just want to enter the ID of the person or at least have more filters. The drop down just does not work the moment you have too much users.

**Comment by zonque** [comment]
This should be fixed by #214, which adds a text field to filter for a person's full name, case insensitive. Could you try the current master and see whether this works for you? Adding the ID to the filter would be trivial to do.

**Comment by ScottyTM** [comment]
I think he means adding conferences for crew members while editing the user Account.

@herrurbach the list should be sorted by date descending AFAICT so the latest conferences should be on top.

**Comment by herrurbach** [comment]
@ScottyTM Na, Conference adding is no problem at all. 

@zonque Uh, I had not the newest master running. This is great. It works like a charm. Thank you!

Closing this as it is done.
