### ISSUE TITLE
Add gravatar support

### ISSUE THREAD

**Issue by olea** [frab/frab#244]
Please add Gravatar support to user profiles: https://en.gravatar.com/site/implement/

**Comment by hellekin** [comment]
Cf. https://wiki.libravatar.org/libraries/#index8h2 for a Libravatar ruby implementation.

**Comment by zonque** [comment]
While I like the idea of Gravar, embedding code to load icons from their side is a privacy issue. Not saying we shouldn't do it, but it's something to consider.

**Comment by manno** [comment]
The solution in #363 will default to Gravatar for every person who has not set an avatar. The image URL will be the Gravatar URL, effectively leaking the email,  md5 encoded, to Gravatar.

Creating new Person models with an avatar will not reach out to Gravatar.

@erdgeist, @ScottyTM any opinions?

Should this be configurable by installation or by user (opt-in for gravatar)?

**Comment by manno** [comment]
Ah I just added another field: ecfe06a885f8ba70539705bc8a20314a57b4199b
