### ISSUE TITLE
Multiple roles in one conference

### ISSUE THREAD

**Issue by olea** [frab/frab#245]
Current user features are not very clear. Digging into sources I check admin can't have a role in a conference and crew can just have one role. I think this is not reallistic. For example a person administering the frab server can be organizer of an event or, most probable, a reviewer.

Please let multiple roles for both crew and admin users.

Thanks for your attention.

**Comment by ScottyTM** [comment]
The Administrator role has full access to frab, he can create new conferences and full access to everything, It can do everything in all conferences that crew and reviewer can do.

The Crew role has full access to a single conference. It can also review talks.

The Reviewer role can only see submissions to a single conference and their own reviews.

One account can be either Admin or crew in multiple conferences and/or reviewer in multiple conferences.
