### ISSUE TITLE
Convert to bootstrap 2 and simple_form

### ISSUE THREAD

**Issue by oneiros** [frab/frab#25]
The switch to bootstrap 2 is long overdue. The blocker is the formtastic-bootstrap gem that has not yet been updated for bootstrap 2. 

simple_form is an alternative to formtastic that offers bootstrap-compatibility out of the box. That is why switching is probably a good idea in the long run, even though the conversion will be annoying...

**Comment by manno** [comment]
I'm closing this. Frab is now using simple_form, but still on bootstrap 1.
