### ISSUE TITLE
ArgumentError: Unknown key: :uniq

### ISSUE THREAD

**Issue by derchrisuk** [frab/frab#250]
Hi,

we are currently trying to setup frab.
While going through the dev setup, it stops after a while with the following error:

`ArgumentError: Unknown key: :uniq. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type`

That is being set in

`app/models/person.rb:  has_many :events, :through => :event_people, :uniq => true`

Looking at the `has_many` doc, `uniq` is not a valid option:

http://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many

I don't know enough about Ruby to fix it at the moment, but could i just remove this option?
Also saw that in one of the last PR there was a change from `group_by` to `uniq`, so maybe this is causing the problem now?

ENV is RVM using Ruby 2.3 on a Debian 8.5

**Comment by manno** [comment]
Looks like the old Rails 3 code. Could you please try the current master?
It should look like this: https://github.com/frab/frab/blob/master/app/models/person.rb#L7

**Comment by derchrisuk** [comment]
I copied it over, and it seems to work now.

**Comment by zonque** [comment]
You should really synchronize the whole tree rather than copying over individual files. They depend on each other, and mixing file from different version will likely give you unexpected results of all sorts.
