### ISSUE TITLE
submitting a new cfp event fails when including a link

### ISSUE THREAD

**Issue by ccoenen** [frab/frab#251]
I tried to add an event in MRMCDs CfP. When I added my proposal, the server would `500` on me. I tried again, this time without a link in the proposal. I guess the link array is not initialised here: https://github.com/frab/frab/blob/master/app/controllers/cfp/events_controller.rb#L46

**steps to reproduce**
1. Login
2. Start adding a cfp event (`<event>/cfp/events/new`)
3. Add some details
4. **Add a link right away!**
5. Submit
6. Examine 500 error :-(

I'm not entirely sure if this is a general problem, or with MRMCD's installation. But I thought I'd raise it here.

**Comment by raphaelm** [comment]
> I'm not entirely sure if this is a general problem, or with MRMCD's installation.

For the record, this is the ``frab.cccv.de`` installation.

**Comment by ccoenen** [comment]
For the record: adding a link after creating the event works just fine. That's why i was suspecting the create action.

**Comment by ShadowBan** [comment]
@manno I was unable to recreate this bug as of commit 10219536a725d5b25fe540dd5ad46a2e466434d0 in my local env.  We may need more information here to get a fix going.

**Comment by ccoenen** [comment]
If anyone could point me to a demo-server, I'd happily re-examine it. It's old enough that it might have gotten fixed over the past few weeks.

**Comment by manno** [comment]
@ccoenen this one should work now: https://frab-staging.froscon.org/

**Comment by ccoenen** [comment]
appears to be fixed.
