### ISSUE TITLE
Better errors when submitting conference settings changes

### ISSUE THREAD

**Issue by rixx** [frab/frab#253]
1. When editing conference settings, clicking "Update conference" apparently submits all pages/tabs of the form (Settings, Days, Tracks, Rooms, Schedule, Notifications).
   This can lead to error messages like "Invalid Color" when the user only tried to add a notifiaction text.
2. Multiple errors will be displayed in one notification bar without whitespace, line breaks or anything in between them. Reproduce by trying to add a notification, but leaving both parts of it empty.

Both of these were spotted on the `frab.cccv.de` installation.

**Comment by manno** [comment]
frab doesn't really have 'tabs' it's just a link to another page, not sure how that happened.

We should fix the layout of the alert area when displaying multiple messages.

**Comment by eladeyal-intel** [comment]
#2 would be fixed by #653 + #547

**Comment by eladeyal-intel** [comment]
#653 and #547 were merged. This issue should be closed.
