### ISSUE TITLE
Rooms in JSON export are objects instead of arrays

### ISSUE THREAD

**Issue by bernd-s** [frab/frab#255]
Hi,

when exporting the schedule as JSON, the rooms property under days has the rooms as objects instead of array elements. In my opinion this should be an array of rooms.

Example:
Current:

```
schedule {
  conference {
    days [
      rooms {
        Room 1: []
      }
    ]
  }
}

```

Expected:

```
schedule {
  conference {
    days [
      rooms [
        Room 1: []
      ]
    ]
  }
}
```

Regards
Bernd

**Comment by bernd-s** [comment]
Having it this way there is no need to now the room names in order to import rooms by parsing the JSON in Java.

**Comment by saerdnaer** [comment]
@bernd-s Your suggestion does not make sense. 
```
      rooms [
        Room 1: []
      ]
```
is not valid JSON. It think your Java Code is the problem – can you post the relevant sections?

**Comment by saerdnaer** [comment]
issue should be closed

**Comment by bernd-s** [comment]
@saerdnaer This is still an issue for me, but the correct JSON would look like this:
`
"schedule": {
  "conference": {
    "days": [
       "2016-01-01" :[
        "Room 1" : []
      ]
    ]
  }
}
`

**Comment by saerdnaer** [comment]
@bernd-s Again: Your example is not valid JSON. JSON arrays aka [] do not have key value pairs, only values – see http://json.org .

**Comment by bernd-s** [comment]
@saerdnaer You are right. So here is another try. This time this should be valid JSON:
`{
  "schedule": {
    "conference": {
      "days": [
          {
            "date": "2016-01-01",
            "rooms": [
              {
                "name": "Room 1",
                "talks": []
              }
            ]
          }
        ]
    }
  }
}`

**Comment by manno** [comment]
@bernd-s Hi, why do you want to change this? I'm afraid that might break several external apps which rely on the existing JSON structure.
