### ISSUE TITLE
Bug with Rooms?

### ISSUE THREAD

**Issue by derchrisuk** [frab/frab#258]
Hi,

during testing I could see an issue with Rooms.
When trying to access the page, I was presented with an error.
And the log was showing following:

`I, [2016-08-28T14:00:13.615726 #25235]  INFO -- : Completed 500 Internal Server Error in 27ms (ActiveRecord: 0.9ms)
F, [2016-08-28T14:00:13.617431 #25235] FATAL -- :
ActionView::Template::Error (undefined method `public' for #<Room:0x000000031f2298>
Did you mean?  public_send):
    3:     = f.input :name
    4:     = f.input :size, input_html: { size: 5 }
    5:     = f.input :rank, input_html: { size: 3 }
    6:     = f.input :public, as: :boolean
    7:     = remove_association_link :room, f
  app/views/conferences/_room_fields.html.haml:6:in `_app_views_conferences__room_fields_html_haml__3392498601957426720_56029440'
  app/helpers/application_helper.rb:63:in `add_association_link'
  app/views/shared/_dynamic_association.html.haml:9:in `_app_views_shared__dynamic_association_html_haml__583983170373981141_55698260'
  app/helpers/application_helper.rb:71:in `dynamic_association'
  app/views/conferences/_form_rooms.html.haml:2:in `block in _app_views_conferences__form_rooms_html_haml__4500672740744484616_55648060'
  app/views/conferences/_form_rooms.html.haml:1:in `_app_views_conferences__form_rooms_html_haml__4500672740744484616_55648060'
  app/views/conferences/edit_rooms.html.haml:17:in `_app_views_conferences_edit_rooms_html_haml__3998323552490482085_54677480'`

Looking at the commits, the removal of the public flag for rooms has been merged sometimes last year.
I had to edit the `app/views/conferences/_room_fields.html.haml` file, and remove the public line.
Is this a bug, and should have the line been removed as part of the merge?

**Comment by manno** [comment]
Yes, that line has to be removed.
