### ISSUE TITLE
Emoji in “Description” field

### ISSUE THREAD

**Issue by JostMigenda** [frab/frab#269]
Encountered this problem while trying to submit a new talk for 33C3 at https://frab.cccv.de/en/33c3/cfp/events/new – I’m not sure whether it’s purely a frab problem or related to their server configuration, but posting this here on [@\_rami\_’s suggestion](https://twitter.com/_rami_/status/781963966553677824):

When creating a new event that includes emoji (in this case: “💣🌟”) in the “Description” field, after I click on “Create event”, I receive an error message (HTTP statuscode 500, see `<title>` tag in the screen shot below) and the event is not created.
After removing the emoji from the description, I was able to create the event. (However, editing the existing event and trying to add the emoji results in the same error and the changes to the event aren’t changed.)
![screen shot of error message](https://cloud.githubusercontent.com/assets/16189747/19010891/636764a4-8780-11e6-8d20-f7a64a924b17.png)

**Comment by manno** [comment]
http://stackoverflow.com/a/34854453

Turns out we're using MySQL :(
