### ISSUE TITLE
Remove access to profiles which are not relevant for the current role

### ISSUE THREAD

**Issue by schneider42** [frab/frab#276]
As a reviewer I do like to see which events have been submitted before by a speaker and what the feedback was.

I think access to these profiles should only be possible if the speaker submitted an event to a conference for which I have reviewing rights. At the moment I can step through every speaker and see all (even rejected) event titles as well as the feedback to these events, submitted to any other conference (of course only conferences handled by the same frab instance).

**Comment by saerdnaer** [comment]
So your are proposing a different frab behavior for persons with reviewer role and persons with coordinator role?

**Comment by manno** [comment]
You are suggesting to hide a speakers previous submissions from a reviewer, if the reviewer has no (reviewer) access to the submissions conference.

Removing this would lead to confusion in discussions among reviewers with different access. Storing this data and making it available to the content team is intentional.
Why  do you want to remove it?

**Comment by schneider42** [comment]
I think I did not make my self clear in the original post. Let me use an example:

I have a reviewing rights for the 33C3, but I can access profiles of people which did not submit anything to the 33C3. I can simply step through https://frab.cccv.de/en/people/1083 and see
* Non public email addresses
* Phone numbers
* All accepted events
* All rejected events
* All feedback to accepted events

I think I should only have access to this information if the person submitted something to 33C3.

**Comment by manno** [comment]
Yes, the intention is to make this data available to the crew, this includes reviewers, so they can make a fully informed decision.
