### ISSUE TITLE
export_confirmed includes availabilites for all conferences

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#284]
The export contains all the speakers including their availabilities, which is fine, but these availabilities are not limited to the current conference which yields much more data than necessary and makes processing harder.

**Comment by manno** [comment]
Fixed in https://github.com/frab/frab/commit/d1f64547b0750786caeee4d144f5655054c5a4e6

Will deploy later...

**Comment by erdgeist** [comment]
An ActionView::Template::Error occurred in events#export_confirmed:

  undefined local variable or method `event' for #<#<Class:0x0000000718cae8>:0x007f7adcb1f748>
  app/views/events/export.json.jbuilder:13:in `block (2 levels) in _app_views_events_export_json_jbuilder__3469295667169575490_70082761687960'

  app/views/events/export.json.jbuilder:13:in `block (2 levels) in _app_views_events_export_json_jbuilder__3469295667169575490_70082761687960'
  app/views/events/export.json.jbuilder:9:in `block in _app_views_events_export_json_jbuilder__3469295667169575490_70082761687960'
  app/views/events/export.json.jbuilder:1:in `_app_views_events_export_json_jbuilder__3469295667169575490_70082761687960'
  app/controllers/events_controller.rb:37:in `block (2 levels) in export_confirmed'
  app/controllers/events_controller.rb:36:in `export_confirmed'

**Comment by erdgeist** [comment]
Fix is simple, the event variable is called "e" in the block and the fix references "event"

**Comment by manno** [comment]
Has been fixed in https://github.com/frab/frab/commit/b6f1267d1e235661bfff0e4312136bcd5d5fd831 and deployed two days ago. Can you test again please?

**Comment by erdgeist** [comment]
Works. Thanks.
