### ISSUE TITLE
Can't create new conference

### ISSUE THREAD

**Issue by manno** [frab/frab#287]
undefined method `any?' for nil:NilClass
  app/views/conferences/_form.html.haml:2:in `block in _app_views_conferences__form_html_haml__4205365317978108220_70136788650080'

  app/views/conferences/_form.html.haml:2:in `block in _app_views_conferences__form_html_haml__4205365317978108220_70136788650080'
  app/views/conferences/_form.html.haml:1:in `_app_views_conferences__form_html_haml__4205365317978108220_70136788650080'
  app/views/conferences/new.html.haml:18:in `_app_views_conferences_new_html_haml__1393537716528907155_70136851082820'
  app/controllers/conferences_controller.rb:68:in `block (2 levels) in create'
  app/controllers/conferences_controller.rb:64:in `create'

**Comment by zonque** [comment]
Hmm. Did you get redirected back to the `new` template after an unsuccessful attempt of saving the conference? In this case, does #288 fix your problem?

**Comment by manno** [comment]
Unclear, the exception came by  mail, I was just looking at it, but #288 should fix it. Thanks 👍
