### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by miclill** [frab/frab#290]
Dear good people,

congratulations for getting prototypefunded. My small suggestion to increase interest is to add some screenshots and / or video.

Thanks

**Comment by manno** [comment]
Thanks. Here are some older screenshots: https://github.com/frab/frab/wiki/Screenshots

**Comment by miclill** [comment]
@manno Thank you for your quick answer. I think a lot of people read the Readme first looking for Screenshots. So maybe it would be good to link to this page.
Regards

**Comment by manno** [comment]
Hmm, good point. I added a link to the screenshots.
