### ISSUE TITLE
Possibility to add categories to the talks 

### ISSUE THREAD

**Issue by tatiweb** [frab/frab#297]
Hi, 

I am admin on FRAB (sha2017) and would like to add categories on the talks but I cant see where I can do this. Is this an existing functionality?

Thanks
Claudia

**Comment by sebix** [comment]
You can assign a talk to a track in the edit event view (/en/[conf-name]/events/[event-id]/edit). There are no categories.

**Comment by wvholst** [comment]
We don't want to use tracks. Because they are mutually exclusive. Something can be about technology *and* politics *and* art, for example.

**Comment by sebix** [comment]
See also #156

**Comment by manno** [comment]
I think this has been implemented by #295
