### ISSUE TITLE
Order rooms in ics export

### ISSUE THREAD

**Issue by cko** [frab/frab#301]
Giggity (Android app) and propably other tools as well show the rooms in the same order as they appear in the ics File. But the order in the ics file isn't (always) the same as configured in frab. Which may lead to sth like "Room B, Room A, Room C" etc.

**Comment by ScottyTM** [comment]
The .ics file is ordered by talk title:

`@conference.events_including_subs.is_public.accepted.order(:title).each do |event|`
see  frab/app/views/public/schedule/index.ics.ri_cal

Most tool use the XML or json export. So we should take a look at  frab/app/views/public/schedule/index.xml.haml:

'@conference.rooms_including_subs.each do |room|' 

looking at  frab/app/models/room.rb with my non-existing ruby skills it looks to me it should be ordered by the rank set in conference settings on the webpage (/en/<conference_id/conference/edit_rooms). 

https://programm.froscon.de/2016/schedule.xml confirms this.

**Comment by manno** [comment]
Indeed, rooms has a default scope and will order by 'room rank'.
If external tools wanted a different order, they'd probably sort themselves.

I'm closing this as there is nothing to do for frab. Thanks for reporting though :)
