### ISSUE TITLE
Make event types configurable

### ISSUE THREAD

**Issue by cko** [frab/frab#302]
some event types like dj set, performance or concert don't fit to every conference. It would be cool, if event types could be configured per conference via the settings.

**Comment by saerdnaer** [comment]
Current workaround: use 'tracks' for addinonal types ;-)

**Comment by eladeyal-intel** [comment]
Updated documentation: 

https://github.com/frab/frab/wiki/Manual/_compare/efac6fc44f4d7f44429dad19e1d64cb626731b86...517425126e9fd0fc6fdb329a65cd82b368f9b871

OK to close, I think.

**Comment by almereyda** [comment]
Yes, it seems this can be closed, since https://github.com/frab/frab/pull/530 has long been merged.
