### ISSUE TITLE
login with not activated account confusing

### ISSUE THREAD

**Issue by saerdnaer** [frab/frab#305]
When user tries to login and mail adress was not confirmed yet, the error message is confusing and suggests a wrong password instead showing an resend activation mail link.

**Comment by manno** [comment]
Could you check if this is still the case?

**Comment by saerdnaer** [comment]
Thanks, issue is fixed:

<img width="1047" alt="temp" src="https://user-images.githubusercontent.com/40266/31821452-708d63b4-b5a5-11e7-8725-802d1513c9aa.png">
