### ISSUE TITLE
View public schedule broken

### ISSUE THREAD

**Issue by raoulb** [frab/frab#306]
The static export is off by one. Say the conference has two days.
The static html also has two days, but the first html page is empty, the second page
displays the events from the first day and there is a 'hidden' url showing a page with
the events from the second day.

This is introduced by #289. With older versions everything works as expected.

**Comment by manno** [comment]
The latest master (https://github.com/frab/frab/commit/2df3aaf901e31117d9fea18715ff7581777a2740) might fix this. Can you test it?

**Comment by raoulb** [comment]
I tested that and unfortunately it does not fix the problem.
The links in the html main page (for two days) are:
```
.../public/schedule/0
.../public/schedule/1
```
but 0 does not exists, instead we should have have:
```
.../public/schedule/1
.../public/schedule/2
```

**Comment by raoulb** [comment]
PR https://github.com/frab/frab/pull/308 should fix this issue.
