### ISSUE TITLE
Typo3 Integration

### ISSUE THREAD

**Issue by Starkmann** [frab/frab#309]
Hi,

i just wanted to let you know that i finally finished the typo3 integration for frab:
https://github.com/Starkmann/frab_integration

Atm it is stable running on 6.2 but i will improve it for 7.6 and 8.7 soon. And also will add some (more) documentation.
I will try to integrate all the jsons views you have.

Right now its:

public/schedule.json
public/speakers.json

**Comment by Starkmann** [comment]
Hmm forgot there was already #54. Was that really in 2013? ;-)

**Comment by manno** [comment]
This is great. I'm going to link to it from the wiki.
