### ISSUE TITLE
UX: several fields that relevant for speakers aren't available to them and vice versa

### ISSUE THREAD

**Issue by wvholst** [frab/frab#313]
The 'tech rider' field and the 'expenses' tab are not available to speakers/submitters while they are relevant to them. Conversely, they can enter a preferred time, which a lot of newbies will do instead of using the speaker availability tab.

**Comment by zonque** [comment]
That's really a matter of how you run your conference. The expenses feature, for instance, is required to be only writeable by administrators in many cases, as they want these expenses to be justified, and not under the control of speakers. Similar for techriders.

That said, it would in theory be possible to change that through configuration parameters, but that significantly increases the test matrix, so I'm not sure whether it's worth it.

**Comment by wvholst** [comment]
To me it would be logical to be able to collect this data without having to trawl through hundreds of submission notes. Likewise for the tech riders.

**Comment by manno** [comment]
more customization would be nice. closed for inactivity
