### ISSUE TITLE
Unable to login after git pull

### ISSUE THREAD

**Issue by gurubert** [frab/frab#325]
I just updated a frab instance via git pull and now I am unable to login.
The credentials are accepted (as no error is displayed) but I am not authorized.
What can I do?

**Comment by manno** [comment]
Check the log file for clues. You should be able to see the login and the resulting redirect in `logs/production.log` for example.

**Comment by gurubert** [comment]
It just redirects me to the list of conferences. The upper right corner still says "Log-In" and "Sign Up".
The logfile records no errors:
Started GET "/users/sign_in?conference_acronym=osdach2017&locale=en" for 87.49.146.167 at 2017-08-04 00:38:12 +0200
Processing by Auth::SessionsController#new as HTML
  Parameters: {"conference_acronym"=>"osdach2017", "locale"=>"en"}
  Conference Load (0.3ms)  SELECT  "conferences".* FROM "conferences" WHERE "conferences"."acronym" = ? LIMIT ?  [["acronym", "osdach2017"], ["LIMIT", 1]]
  Rendering vendor/bundle/ruby/2.3.0/gems/devise-4.3.0/app/views/devise/sessions/new.html.erb within layouts/application
  Rendered vendor/bundle/ruby/2.3.0/gems/devise-4.3.0/app/views/devise/shared/_links.html.erb (1.7ms)
  Rendered vendor/bundle/ruby/2.3.0/gems/devise-4.3.0/app/views/devise/sessions/new.html.erb within layouts/application (11.2ms)
  Rendered shared/_navi_cfp_login.html.haml (1.7ms)
  Rendered shared/_flash.html.haml (2.8ms)
Completed 200 OK in 88ms (Views: 28.2ms | ActiveRecord: 1.7ms)


Started POST "/users/sign_in?conference_acronym=osdach2017&locale=en" for 87.49.146.167 at 2017-08-04 00:38:17 +0200
Processing by Auth::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"UknhCS5Znb7rPz9f9QAeQS4lSwuTsygUit3wGgscWUfXtZbQWU3Lwu4RAMRYY7d1US/hgpv1OTTYoXpoodaQwQ==", "user"=>{"email"=>"r.sander@openstack-dach.org", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Log in", "conference_acronym"=>"osdach2017", "locale"=>"en"}
  Conference Load (0.3ms)  SELECT  "conferences".* FROM "conferences" WHERE "conferences"."acronym" = ? LIMIT ?  [["acronym", "osdach2017"], ["LIMIT", 1]]
HTTP Origin header (https://events.openstack-dach.org) didn't match request.base_url (http://events.openstack-dach.org)
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? ORDER BY "users"."id" ASC LIMIT ?  [["email", "r.sander@openstack-dach.org"], ["LIMIT", 1]]
  Person Load (0.2ms)  SELECT  "people".* FROM "people" WHERE "people"."user_id" = ? LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
   (0.1ms)  begin transaction
  SQL (1.6ms)  UPDATE "users" SET "sign_in_count" = ?, "current_sign_in_at" = ?, "last_sign_in_at" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["sign_in_count", 26], ["current_sign_in_at", "2017-08-03 22:38:18.071469"], ["last_sign_in_at", "2017-08-03 22:20:50.059556"], ["updated_at", "2017-08-03 22:38:18.073176"], ["id", 1]]
   (3.4ms)  commit transaction
Redirected to http://events.openstack-dach.org/?conference_acronym=osdach2017&locale=en
Completed 302 Found in 182ms (ActiveRecord: 5.9ms)


Started GET "/?conference_acronym=osdach2017&locale=en" for 87.49.146.167 at 2017-08-04 00:38:18 +0200
Processing by HomeController#index as HTML
  Parameters: {"conference_acronym"=>"osdach2017", "locale"=>"en"}
  Conference Load (0.3ms)  SELECT  "conferences".* FROM "conferences" WHERE "conferences"."acronym" = ? LIMIT ?  [["acronym", "osdach2017"], ["LIMIT", 1]]
  Rendering home/index.html.haml within layouts/application
  Conference Exists (0.1ms)  SELECT  1 AS one FROM "conferences" LIMIT ?  [["LIMIT", 1]]
  SQL (0.3ms)  SELECT  DISTINCT "conferences"."id" FROM "conferences" LEFT OUTER JOIN "days" ON "days"."conference_id" = "conferences"."id" LEFT OUTER JOIN "call_for_participations" ON "call_for_participations"."conference_id" = "conferences"."id" WHERE ("days"."end_date" > '2017-08-03 22:38:18.205909') ORDER BY days.start_date DESC LIMIT ? OFFSET ?  [["LIMIT", 10], ["OFFSET", 0]]
  SQL (0.5ms)  SELECT DISTINCT "conferences"."id" AS t0_r0, "conferences"."acronym" AS t0_r1, "conferences"."title" AS t0_r2, "conferences"."timezone" AS t0_r3, "conferences"."timeslot_duration" AS t0_r4, "conferences"."default_timeslots" AS t0_r5, "conferences"."max_timeslots" AS t0_r6, "conferences"."feedback_enabled" AS t0_r7, "conferences"."created_at" AS t0_r8, "conferences"."updated_at" AS t0_r9, "conferences"."email" AS t0_r10, "conferences"."program_export_base_url" AS t0_r11, "conferences"."schedule_version" AS t0_r12, "conferences"."schedule_public" AS t0_r13, "conferences"."color" AS t0_r14, "conferences"."ticket_type" AS t0_r15, "conferences"."event_state_visible" AS t0_r16, "conferences"."schedule_custom_css" AS t0_r17, "conferences"."schedule_html_intro" AS t0_r18, "conferences"."default_recording_license" AS t0_r19, "conferences"."expenses_enabled" AS t0_r20, "conferences"."transport_needs_enabled" AS t0_r21, "conferences"."parent_id" AS t0_r22, "conferences"."bulk_notification_enabled" AS t0_r23, "conferences"."logo_file_name" AS t0_r24, "conferences"."logo_content_type" AS t0_r25, "conferences"."logo_file_size" AS t0_r26, "conferences"."logo_updated_at" AS t0_r27, "days"."id" AS t1_r0, "days"."conference_id" AS t1_r1, "days"."start_date" AS t1_r2, "days"."end_date" AS t1_r3, "call_for_participations"."id" AS t2_r0, "call_for_participations"."start_date" AS t2_r1, "call_for_participations"."end_date" AS t2_r2, "call_for_participations"."hard_deadline" AS t2_r3, "call_for_participations"."welcome_text" AS t2_r4, "call_for_participations"."conference_id" AS t2_r5, "call_for_participations"."created_at" AS t2_r6, "call_for_participations"."updated_at" AS t2_r7, "call_for_participations"."info_url" AS t2_r8, "call_for_participations"."contact_email" AS t2_r9 FROM "conferences" LEFT OUTER JOIN "days" ON "days"."conference_id" = "conferences"."id" LEFT OUTER JOIN "call_for_participations" ON "call_for_participations"."conference_id" = "conferences"."id" WHERE ("days"."end_date" > '2017-08-03 22:38:18.205909') AND "conferences"."id" = 1 ORDER BY days.start_date DESC
  Rendered home/_table.html.haml (6.4ms)
  Rendered home/index.html.haml within layouts/application (20.6ms)
  Rendered shared/_navi_cfp_login.html.haml (1.6ms)
  Rendered shared/_flash.html.haml (2.7ms)
Completed 200 OK in 38ms (Views: 33.0ms | ActiveRecord: 1.3ms)

**Comment by manno** [comment]
Hm, having "Sign In" buttons is usually a strong indicator that log in didn't work.
I wonder if this is related to this:
>  HTTP Origin header (https://events.openstack-dach.org) didn't match request.base_url (http://events.openstack-dach.org)

Maybe there are headers missing from nginx/apache (whoever does SSL)?  Like in this issue https://github.com/rails/rails/issues/22965 maybe?

**Comment by gurubert** [comment]
Thank you for the hint to the rails issue. That was the solution.
I upgraded from a version of frab cloned in March and now I had to add
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on; # Optional
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Host $host;
to the nginx configuration.
