### ISSUE TITLE
Permissions change depending on the page i login

### ISSUE THREAD

**Issue by tatiweb** [frab/frab#326]
Please, close this issue if it is due to the installation settings. 
I have the idea it has to do with the flow structure from FRAB itself, though:

1- if i go to 
![fireshot screen capture 001 - sha2017 - call for participation - httpsfrab sha2017 orgensha2017cfpsessionnew](https://user-images.githubusercontent.com/846638/29240544-daf6ddee-7f67-11e7-90ba-be407e5ba47c.png)
And login from there, i am a submitter.

2- With the same credentials, if i login on the (for us, admin login page) 
![fireshot screen capture 006 - frab - conference management - frab_sha2017_org_en_session_new_conference_acronym sha2017 return_to 2f](https://user-images.githubusercontent.com/846638/29240563-34ac6a2a-7f68-11e7-8e00-ba7b595255ba.png)
I have admin rights

**Comment by manno** [comment]
The different areas of frab are confusing. However that behaviour changed a lot recently. When was this servers last update?

**Comment by manno** [comment]
closed for inactivity. different areas are probably still confusing.
