### ISSUE TITLE
It would be nice to be able to filter and search instead of the reports page

### ISSUE THREAD

**Issue by tatiweb** [frab/frab#327]
During the management of the conference, the reports area was very unsatisfying as we needed to make custom searches. 

![fireshot screen capture 016 - sha2017 - conference management - frab_sha2017_org_en_sha2017_reports](https://user-images.githubusercontent.com/846638/29240609-d99098d6-7f68-11e7-922c-1f72b9b6f84e.png)

**Comment by manno** [comment]
I still want to see elasticsearch in frab. We've been using it in [voctoweb](https://github.com/voc/voctoweb/) with great success. However it's a heavy dependency and only makes sense for large conferences. So it's probably not going to happen, unless someone makes a PR.

In the meantime, @erdgeist  re-implemented the filters for events (https://github.com/frab/frab/commit/7daab844f9acc0f37c1087841637193fd62ee5c9) recently. Does this help?

**Comment by eladeyal-intel** [comment]
Fixed by #579. Issue should be closed.
