### ISSUE TITLE
remote database host?

### ISSUE THREAD

**Issue by lanrat** [frab/frab#329]
When configuring `/config/database.yml`, how can I specify a hostname or IP for a postgresql or mysql database?

Frab seems to only use local sockets, but I need a way to specify a remote host for the database.

Is this possible?

**Comment by manno** [comment]
Since frab is a Rails application you can follow http://guides.rubyonrails.org/configuring.html#configuring-a-database

Either use DATABASE_URL as an env var, or put the `host:` key in the `database.yml`.

**Comment by lanrat** [comment]
Thanks, that is exactly what I was missing!
