### ISSUE TITLE
Add a "Access-Control-Allow-Origin: *" to the schedule/speaker json/xml

### ISSUE THREAD

**Issue by stijink** [frab/frab#335]
Hi,

i'm on my way of programming an little web based single page app around the schedule and speaker data you guys provide.

Unfortunately i cannot access this data via ajax directly from the javascript app, since the browser blocks calls the other domains by default.

One way to come around this is to add a special header on your side on the output of the json and/or xml file.

This would look like this:
`Access-Control-Allow-Origin: *`

You can find more informations on this topic here: 
https://www.eriwen.com/javascript/how-to-cors/

If you would point me to the file / files where to handle this i could also do a pull request myself :-)

Thanks,
Stephan

**Comment by zonque** [comment]
That's already done in 1592d5464. Could you check the latest version and report if that works for you?

**Comment by stijink** [comment]
@zonque Ah, nice. Actually i was testing against the froscon page. It seems that this change hasn't made it onto that system by now :-) One of the crew members (?) (Bernd Schönbach) pointed me to github :-)

**Comment by zonque** [comment]
Fair enough. You may tell them it's easy to just cherry-pick this commit, in case they don't want to update their entire system yet.

**Comment by manno** [comment]
@stijink  I updated their server, can you check?
