### ISSUE TITLE
speakers can't save their availability

### ISSUE THREAD

**Issue by luto** [frab/frab#337]
When a speaker logs into their account to change the availability, the form is presented like normal, but there is no way to save it. It looks like [`287ebd6`](https://github.com/frab/frab/commit/287ebd68f8be4967b488747fa2be2a1884318a8a#diff-192804dd9d526d67549ab494d058fe47L10) introduced this behavior, by changing the condition from `if can? :crud, person` (can edit _person_) to `if policy(@conference).manage?` (can edit _conference_). While this change makes sense for the admin view of things, it does not for the speakers.

In case you need any additional information, please just ping me. Thanks.

**Comment by luto** [comment]
Thanks for your quick fix!

**Comment by bascht** [comment]
I'm not sure if 8198243 fixes this entirely. We're on the latest frab/frab master but the button still doesn't show for users that only have the role `submitter`. 

Is there anything we can contribute to help debugging this any further?

**Comment by manno** [comment]
I added a test for this (https://github.com/frab/frab/commit/7dd28f271db130a2b91e7865e1a752fa0c90f62e) and I can't think of any reason why the button should still be missing.

You have this line https://github.com/frab/frab/blob/master/app/policies/person_policy.rb#L17 in your deployment?

**Comment by bascht** [comment]
@manno Darn it. I checked both app servers and we had deployed the latest revision but apparently not restarted the app. 😭  Sorry for the noise 😄
