### ISSUE TITLE
Add frab base_url to schedule.xml/json header

### ISSUE THREAD

**Issue by saerdnaer** [frab/frab#338]
If one wants to resolve the file attachments referenced inside a schedule xml one has to prefix the path with an hostname/base-url. 

For example:
```xml
<attachment href="/system/event_attachments/attachments/000/003/131/original/talk_33c3_netzpolitik.pdf?1482965202">Sldies</attachment>
```
one needs to add https://frab.cccv.de/ to get  the full URL https://frab.cccv.de/system/event_attachments/attachments/000/003/131/original/talk_33c3_netzpolitik.pdf

I propose a new child element named **base_url** directly below the root node:
```xml
<schedule>
  <version>1.3</version>
  <base_url>https://frab.cccv.de/</base_url>
  <conference>
    <acronym>33c3</acronym>
    <title>33. Chaos Communication Congress</title>
    <start>2016-12-27</start>
    <end>2016-12-30</end>
    <days>4</days>
    <timeslot_duration>00:15</timeslot_duration>
  </conference>
…
```

```json
{
"schedule": {
  "version": "1.3",
  "base_url": "https://frab.cccv.de/",
  "conference": {
    "acronym": "33c3",
    "title": "33. Chaos Communication Congress",
    "start": "2016-12-27",
    "end": "2016-12-30",
    "daysCount": 4,
    "timeslot_duration": "00:15",
```

**Comment by manno** [comment]
Indeed, do you think the base url should be there, or should we just prepend the base url to all the links?  I think with the QR Code in the public schedule the base_url is already mandatory.

**Comment by saerdnaer** [comment]
We also could do both. There are also other use cases fora base_url, e.g. generation of URLs to the event/speaker pages or images. And there are similar caes with the event logo, c.f. https://c3voc.de/wiki/schedule#full_example

**Comment by manno** [comment]
Quick note:  

* we need a validation on base_url, has to be a full URL for QR Code to work.
* prepend base_url to all links
* add base_url to json, so consumers don't have to deduct it
