### ISSUE TITLE
Fix title for schedule pages

### ISSUE THREAD

**Issue by fhemberger** [frab/frab#340]
I noticed this issue as I was bookmarking a couple of interesting talks during the last congress:

![](https://user-images.githubusercontent.com/153481/29957640-da930a58-8eee-11e7-8591-af30448abe96.png)

There's no distinction in the page's `title` attribute on schedule pages. I came up with a quick fix at least for the public event detail pages in the [template](https://github.com/frab/frab/blob/master/app/views/layouts/public_schedule.html.haml#L6) itself:

```diff
-    %title= title
+    - title_fragments = []
+    - event = @view_model.event if @view_model
+    - if event
+      - event_type = t "options.#{event.event_type.present? ? event.event_type : 'other' }"
+      - title_fragments.push "#{event_type.capitalize}: #{event.title}"
+      - if @conference.days.length > 1
+        - title_fragments.push event.start_time.strftime("%A")
+    - title_fragments.push title
+    %title= title_fragments.join ' | '
```

This will give you titles like

```
Meeting: Recalled to Life | Wednesday | Schedule Azrael Machine Conference
Workshop: From Here to Eternity | Wednesday | Schedule Azrael Machine Conference
```

which are much more expressive, but I think other schedule pages should be treated the same way. Since I'm no Rails expert, I don't know where the best place is to handle such a general approach, so I'm leaving this issue here for discussion.

This will also improve search engines results.

**Comment by manno** [comment]
I agree, I'd solve it with `content_for` and helper methods. However I didn't have time yet to come up with proper translations and didn't really test it.

**Comment by fhemberger** [comment]
@manno Resurrecting this issue as 'twas the time before xxC3: Sad to see that bug still exists. If you need help with translation/testing/whatever let me know, but this regularly annoys me. ;)

**Comment by manno** [comment]
He @fhemberger  apparently this was never merged and closed by accident?
Luckily I found the old commit an put it in a PR.

**Comment by fhemberger** [comment]
Awesome, thank you!
