### ISSUE TITLE
Speakers want to export and import their profile

### ISSUE THREAD

**Issue by manno** [frab/frab#341]
Offer a buttons to download the speakers profile (like name, description, email and logo) and upload it to another frab instance.
I'm sure there is some standard based on XML for speaker data?

**Comment by saerdnaer** [comment]
You could use the XML or JSON variants of FOAF:
* XML examples: http://www.xml.com/pub/a/2004/02/04/foaf.html
* JSON examples: https://en.wikipedia.org/wiki/JSON-LD#Example
* Meta FOAF
  * https://en.wikipedia.org/wiki/FOAF_(ontology)
  * http://www.foaf-project.org
