### ISSUE TITLE
Date chooser in day settings is broken

### ISSUE THREAD

**Issue by luto** [frab/frab#346]
When adding a day on [`/en/xxx/conference/edit_days`](http://localhost:3000/en/xxx/conference/edit_days) the date chooser in either datetime field does not work. Clicking on a day just yields the following javascript error message in the developer console:

```
The specified value "2017-09-27 00:00" does not conform to the required format.  The format is "yyyy-MM-ddThh:mm" followed by optional ":ss" or ":ss.SSS".
```

This is in Chromium 61 on english linux.

**Comment by manno** [comment]
Couldn't reproduce on firefox. Probably the jQuery Timepicker Addon  (v1.6.1 - 2015-11-14) not working with the native datetime inputs of Chrome?

**Comment by MacLemon** [comment]
Can confirm that this does not work in Chrome, Chromium 63.0.3219.0.
