### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ligi** [frab/frab#367]
Unfortunately this typo cannot be fixed via PR - you have to do this on github:

![selection_188](https://user-images.githubusercontent.com/111600/32420462-ab551180-c258-11e7-8227-2444857f6cbe.png)

manangement -> management

**Comment by manno** [comment]
Thanks!

**Comment by ligi** [comment]
You are very welcome!

**Comment by rakekniven** [comment]
Typo is still visible

**Comment by manno** [comment]
Original report was about github.com/frab :) Thanks
