### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by vnaddeo** [frab/frab#370]
I'm a chair of international conference on WaterEnergyNEXUS and I'd like to use your software. Can you help me to instal it, or share an account that I can use for the next edition of the conference?
I will very grateful for your support and of course I'll give you all credits on the website and during the event.
All the best
Vincenzo
___________________________________________
Vincenzo Naddeo, Ph.D
Associate Professor in Environmental Engineering

Sanitary Environmental Engineering Division (SEED)
Department of Civil Engineering
University of Salerno - Via Giovanni Paolo II #132
84084 Fisciano (SA) Italy

tel. +39 089 96 9333 (IT)
fax +39 089 96 9620 (IT)
mobile +1 305 520 9887 (USA)
e.mail vnaddeo@unisa.it
web  www.seed.unisa.it
twitter https://twitter.com/Vincenzo_Naddeo

**Comment by manno** [comment]
I'm sorry there is no free  support for frab. I hope this changes in the future.
