### ISSUE TITLE
Fehler beim Laden "34c3": Network I/O problem: java.io.IOException: Download error

### ISSUE THREAD

**Issue by Wikinaut** [frab/frab#386]
See https://github.com/Wilm0r/giggity/issues/41 .

@erdgeist told me, I should notify you about the problem, that the QR code on https://events.ccc.de/congress/2017/Fahrplan/qrcode.html appears to be incorrectly generated as mentioned in the comments to https://github.com/Wilm0r/giggity/issues/41 .

**Comment by manno** [comment]
The `//fahrplan.events.ccc.de/congress/2017/Fahrplan/` URL seems to have been put there intentionally. I'll change it to https.

**Comment by Wikinaut** [comment]
@manno https://events.ccc.de/congress/2017/Fahrplan/qrcode.html has still the incorrect QR code, when do you change it?

**Comment by manno** [comment]
Sorry should have said that earlier: I can't, orga team has to publish another schedule (@erdgeist maybe?)

**Comment by Wikinaut** [comment]
@erdgeist issue pinged back to you

**Comment by mmuman** [comment]
The "//.." thing is a protocol-relative URI, to avoid mixed-content, I think we can fix Giggity to assume https there. But still it needs the URL to the XML.
I think it should even be possible to add support in frab to generate the JSON format Giggity uses internally that has some more infos (room coordinates, links...).
