### ISSUE TITLE
rails db:migrate RAILS_ENV=development cannot migrate properly

### ISSUE THREAD

**Issue by rameshjesswani** [frab/frab#393]
I am trying to run frab by following steps of installation from https://github.com/frab/frab/blob/master/INSTALL.md

When I try to run the server by executing command: `` rails server``

I get error:

 
 Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=development

when I execute `rails db:migrate RAILS_ENV=development` 

Then **I get error**: 
```
== 20120328113456 AddSpeakerCounter: migrating ================================
-- add_column(:events, :speaker_count, :integer, {:default=>0})
   -> 0.0015s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Couldn't find Event with 'id'=all
C:/Users/kuma_rm/github/frab/db/migrate/20120328113456_add_speaker_counter.rb:6:
in up
bin/rails:4:in require
bin/rails:4:in <main>

Caused by:
ActiveRecord::RecordNotFound: Couldn't find Event with 'id'=all
C:/Users/kuma_rm/github/frab/db/migrate/20120328113456_add_speaker_counter.rb:6:
in up
bin/rails:4:in require
bin/rails:4:in <main>
Tasks: TOP => db:migrate
(See full trace by running task with --trace)


Furthermore, in link during step 5(Modify settings), I do not understand, what I have to modify, so I do not follow that step?
 
```
System Configuration:
Windows 7
ruby 2.4.3p205 (2017-12-14 revision 61247) [i386-mingw32]
nodejs version : 9.3.0
rails version: 5.1.4

Thanks in advance
Your help will be appreciated

**Comment by manno** [comment]
Use `rails db:setup`. instead of migrate for new installations.

INSTALL.md mentions running `bin/setup` which in theory should have run `db:setup` from https://github.com/frab/frab/blob/master/bin/setup#L29

**Comment by rameshjesswani** [comment]
Thanks it worked 👍
