### ISSUE TITLE
Active Sub Conference is not showing up on home screen

### ISSUE THREAD

**Issue by daja77** [frab/frab#409]
In the frab homescreen only parent conference are listed under current and also under past because the conferences model is joined witd days to decide in which category they fell.

```  
scope :future, -> { includes(:days).where(Day.arel_table[:end_date].gt(Time.now)).order('days.start_date DESC').distinct }
```

As far as I can see the subconference has no entries in the days table because it inherits its days from the parent, is there a simple fix for that, it is confusing our users a lot.

Thank you.

**Comment by manno** [comment]
@zonque any suggestions?

**Comment by daja77** [comment]
Thanks for the quick reply, unfortunately this patch results in the following error

```
F, [2018-02-13T12:21:30.746008 #1780] FATAL -- : [417ac470-8d7d-4895-af15-b376060efac1]   
F, [2018-02-13T12:21:30.746510 #1780] FATAL -- : [417ac470-8d7d-4895-af15-b376060efac1] NoMethodError (undefined method `includes' for #<Array:0x000000000538ddd0>
Did you mean?  include?):
F, [2018-02-13T12:21:30.746577 #1780] FATAL -- : [417ac470-8d7d-4895-af15-b376060efac1]   
F, [2018-02-13T12:21:30.746655 #1780] FATAL -- : [417ac470-8d7d-4895-af15-b376060efac1] app/controllers/home_controller.rb:3:in `index'
```

**Comment by daja77** [comment]
Thanks for the quick reply, the workaround does the job, the same could be done to the past conferences, but this is not important atm. 
Maybe it is possible to do this in SQL, have to think about it.

Offtopic: We like it very much that frab supports sub-conferences. :)

**Comment by manno** [comment]
I believe PR #411 fixed this

**Comment by zonque** [comment]
Yes, this seems to be a proper fix. Sorry for not responding earlier - I was travelling for awhile when this came up and haven't quite caught up with by backlog yet. Thanks a bunch for cleaning up after me!
