### ISSUE TITLE
changing account email: "leave blank if you don't want to change it" advice for password changes is invalid

### ISSUE THREAD

**Issue by wasamasa** [frab/frab#421]
I'm trying to change my email address for an account.  If I heed the advice to leave the password field blank, it doesn't actually work out for me.

![20180501_173803](https://user-images.githubusercontent.com/3588994/39479796-983314f0-4d66-11e8-8504-6487c378a8df.png)

edit: More amusingly, if I enter my existing password twice, it doesn't actually allow me to proceed any further. If I've checked the option for staying logged in before, I get a blank screen, if I didn't, I get "You need to sign in or sign up before continuing.". Not sure whether related or best left for a separate bug report.

edit2: It's another weirdness because I do get a confirmation e-mail which allows me to proceed. Still, it's rather weird and unexpected. I'd rather have a different screen telling me that I'm almost done and only need to confirm the new email.  Or alternatively, display a success message with a note above telling me about the pending confirmation.

**Comment by manno** [comment]
Interesting, the crew account controller has special logic to handle empty passwords, the one for submitters does not: https://github.com/frab/frab/blob/master/app/controllers/users_controller.rb#L44

I'm surprised Devise re-sends a confirmation mail, nice.

The blank screen might be a authentication issue after changing credentials (devise session deleted?) or a redirect problem.

Are you using any cookie blocking privacy addons? Your last conference should be in your session.

However it's still a bug, the [CFP URL helpers](https://github.com/frab/frab/blob/master/app/controllers/cfp/users_controller.rb#L12) should not be called without a conference.

The fallback logic in [load_conference](https://github.com/frab/frab/blob/master/app/controllers/application_controller.rb#L38) can't always find a conference.

**Comment by wasamasa** [comment]
The only change I'm aware of is changing my browser settings to block third-party cookies from sites I haven't visited before. I applied this long time before trying to change my password though.

**Comment by manno** [comment]
- [ ] implement empty password logic from users controller in crew account controller
- [ ] check if email change is possible for crew
