### ISSUE TITLE
Login button changes to "Create user" after clicking before redirect to next page

### ISSUE THREAD

**Issue by wasamasa** [frab/frab#422]
![20180501_190741](https://user-images.githubusercontent.com/3588994/39483535-01f3c55e-4d73-11e8-9e19-7568cf2c365d.png)

Not sure what the proper translation should be, but definitely something else than that.

**Comment by manno** [comment]
Which URL is that? But it's probably just a translation bug. Are  you using German locales? frab was recently changed to guess users locale and we have a lot of missing tranlsations (https://github.com/frab/frab/issues/416).

**Comment by manno** [comment]
Yes, it's a problem with the newly introduced i18n-lookup gem

* https://stackoverflow.com/questions/13547144/i18n-for-model-specific-rails-submit-button
* https://github.com/frab/frab/blob/master/config/locales/de.yml#L448
