### ISSUE TITLE
CfP interface disallows submissions when soft limit is hit

### ISSUE THREAD

**Issue by towo** [frab/frab#425]
We just had the problem that we've configured the CfP to end on May 23rd 2018, with a hard limit of sometime in 2023.

The "participate" link disappears as soon as the time limit is hit; this behaviour can be shown by just editing the end date.

**Comment by manno** [comment]
I guess it's still possible to submit, if you know the URL?

But you'd expect the button to be there, even though the soft limit has been reached? Wouldn't that lead to more submissions after the deadline?

**Comment by towo** [comment]
Well, the differentation between the soft and the hard limit is that the hard limit really disallows submitting stuff, and the soft limit is a) the communicated date in the software and b) just warns you that you're submitting past the deadline and will be treated accordingly.
