### ISSUE TITLE
Subconference Call for Papers has no submit button

### ISSUE THREAD

**Issue by Duckattack** [frab/frab#430]
I created a subconference and started the call for papers. The url given in the CfP tab (https://frab.froscon.de/users/sign_in?conference_acronym=deRSE18&locale=de) sends you to a login page with no information. 
https://frab.froscon.de/en/deRSE18/cfp/ shows the CfP text, but has no submit button and only the small SignUp link in the top right corner.
Do I have the wrong URL or is there something wrong?

**Comment by manno** [comment]
You have to login first, before a submit button appears. That changed recently.

Cfp tab should probably show the cfp welcoming page url (`/:acronym/cfp`).
The welcoming page needs login/register buttons and an explanatory text.
