### ISSUE TITLE
Devise Emails are all HTML and considered SPAM

### ISSUE THREAD

**Issue by stefek99** [frab/frab#436]
Took me a while to figure out...

**Comment by manno** [comment]
This is probably about the sign-up email, which is only sent as HTML by Devise?

**Comment by stefek99** [comment]
Signup.

![image](https://user-images.githubusercontent.com/249703/47007864-0f97a800-d131-11e8-982c-f1468bc7dac0.png)

**Comment by manno** [comment]
Ok, we need custom controllers and text templates for all the devise emails.

https://github.com/plataformatec/devise/issues/2341
