### ISSUE TITLE
[featurerequest] Link to video in schedule event pages

### ISSUE THREAD

**Issue by laryllian** [frab/frab#444]
Dear wonderful frab makers,
would it be possible to add a video link to the info box on the right side in the schedule event pages? Usually, recording crews such as c3voc use the frab variable called slug to name the recordings. "Slug" is based on the event number and the title. I guess(!) what's necessary would be:

- A new switch in Settings - Programm: "Add links to videos on events pages" (binary, default no)
- A new text field in Settings - Programm: "Basepath of the conference videos" (string e.g. https://media.ccc.de/v/, default empty)
- Code that adds the video link in the schedule's events pages' info box (where recording
is set to true) like: "Video: $basepath/$slug"

That would make so many people happy, from the Congress folks to the Bits&Bäume crowd. :D

Happy greetings and thank you so much

**Comment by laryllian** [comment]
Like this, but really working: https://fahrplan.bits-und-baeume.org/events/245.html ;)

**Comment by saerdnaer** [comment]
As a workaround: For some conferences this was done via adding a link per SQL query on all events.

**Comment by manno** [comment]
We support this for some time (~5 years): https://github.com/frab/frab/blob/master/app/views/public/schedule/event.html.haml#L71-L74

However conference crew has to import the video urls to frab, then run a new program export.
The [manual](https://github.com/frab/frab/wiki/Manual) mentions a rake task `frab:video_import` to do import several URLs at once. It should actually be compatible with `podcast.xml`.

Main problem is no one ever got around styling the html5 player and nobody uses it. I understand it's some manual work, but I prefer it to some magic based  on the slug and conventions. I feel those conventions change every year and frab features should be usable without VOC and voctoweb.

**Comment by laryllian** [comment]
Thanks for the info and your thoughts. My reasoning however is the following: Frab is for conference planning/coordination and schedule generation, not for showing videos or designing html5 players or pulling external content (probably that's why no one styles the player). Presenting videos is IMHO neither frab's scope or task. So for me, the nice and clean solution would be a simple but prominent video link in the event pages, nothing more, as easy as that. This would hand over the video task to a special video provider, yet it would let schedule users actually know, that there is a video and where it is.

As for the frab:video_import: Having read the manual, I have no idea what exatly to import and how. Is there a more detailed specification? Inferring from not really ever having seen this feature being used (congress is probably the biggest use of frab and everyone craves for that feature), I would guess its just too complicated to use as it is for me, which it doesn't have to be. (Where can I see it being used to check it out?)

My wish would be to make this feature more usable so it will in effect actually be used (e.g. my me, hehe). Therefore I would suggest to use and define slug as "ID" and for that, discuss the conventions to make it a stable "frab standard". This is not about VOC, they would probably also addapt to the fixed format, if frab folks decide to fix it. Do you know why it changes every year?

Thanks so much for your work and considerations :D

**Comment by manno** [comment]
I see, so we wouldn't embed a player. This makes things easier and we could remove the old video_import feature, that would be nice.


The slug doesn't really change, I meant the format of the slug, like when we introduced multi language videos. And how to derive the video file from the slug, folder structure etc. changes a lot. But that wouldn't matter.

Example: https://events.ccc.de/congress/2015/Fahrplan/events/7331.html
Not working anymore, for reasons?

My issues with your approach, if I understand correctly now:

* video site would have to work with 'base_url+slug'. voctoweb does of course, but honestly I think most conferences would just like to use youtube.
* no detection for missing videos (dead link)
* no embedded player ;) 

We could just add a `video_url` field to the events table. If we want to fill it automatically for Congress I'll just do it via rails console or we write a small client to talk JSON to https://github.com/frab/frab/blob/master/app/controllers/events_controller.rb#L154-L168 adding the URL via the VOC release pipeline.

**Comment by manno** [comment]
PR #453 removes the old video table and adds a simple text field instead. Import of https://media.ccc.de/c/35c3/podcast/mp4-lq.xml should still be possible via rake task.

**Comment by manno** [comment]
I think I  prefer the old way, of adding the video to the 'links' of a talk.

ping @erdgeist

**Comment by manno** [comment]
Merged the PR, video url is now a text field on event. Will be shown below links in event view.
If someone wants to PR a 'video_base_url'+'event.slug' feature on top of this, please go ahead :)
Probably possible to set the `video_url` to the generated string in an `after_save` on event, if the feature is toggled.
