### ISSUE TITLE
STARTTLS error when sending email

### ISSUE THREAD

**Issue by MisterGlass** [frab/frab#446]
I have a new install up on AWS. I have it configured to use SES to send emails, but whenever the server attempts to send an email (such as during signup) it fails.

Logs:
```
INFO -- : Completed 500 Internal Server Error in 68ms (ActiveRecord: 9.6ms)
FATAL -- : 
FATAL -- :  Net::SMTPAuthenticationError (530 Must issue a STARTTLS command first):
FATAL -- : 
FATAL -- :  /usr/share/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/net/smtp.rb:981:in `check_auth_response'
```

Config:
```
SECRET_KEY_BASE=REDACTED
RUBY_VERSION=2.5.3
FRAB_HOST=https://frab.example.org
FRAB_PROTOCOL=https
FROM_EMAIL=cfp-mailer@example.org
SMTP_ADDRESS=email-smtp.us-east-1.amazonaws.com
SMTP_PORT=587
SMTP_DOMAIN=frab.example.org
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_NOTLS=false
SMTP_USER_NAME=REDACTED
SMTP_PASSWORD=REDACTED
FRAB_CURRENCY_UNIT="€"
FRAB_CURRENCY_FORMAT="%n%u"
```

**Comment by MisterGlass** [comment]
I dug into the config code a bit, found https://github.com/frab/frab/blob/master/config/initializers/action_mailer.rb#L12

Seems like the value of the env setting is ignored, and if this is at all present it effects things. That was not the behavior I expected.

I commented out the setting in my env and its now working.

**Comment by MaxRink** [comment]
Im running into the same Issue but dropping SMTP_NOTLS from my env vars doesnt help

**Comment by manno** [comment]
Should we change the intializer to?

```
 if ENV.fetch('SMTP_NOTLS', 'false') == 'true'
```
So it would be false if absent and only disable TLS, if set to 'true'?
