### ISSUE TITLE
Not returning to schedule after rating

### ISSUE THREAD

**Issue by katrinleinweber** [frab/frab#456]
The `Return to the schedule`-link on the `Thank you!` page after rating an event seems to lead astray.

https://frab.cccv.de/en/35c3/public/schedule/3 => https://frab.cccv.de/users/sign_in => https://frab.cccv.de/de/35c3/cfp/person

Shouldn't it rather link back to https://fahrplan.events.ccc.de/congress/2018/Fahrplan/events.html ?

The responsible line of code might be: https://github.com/frab/frab/blob/4e1bda574fb10cbdda0d6846114b8a447d7c1222/app/views/public/feedback/thank_you.html.haml#L10

Maybe the `conference` slug should be different, or the base URL?

I noticed the same problem when rating https://fahrplan.bits-und-baeume.org/events.html, also in a different browser than the one I used to submit an event proposal.

**Comment by manno** [comment]
Yes, that's missing another if statement
