### ISSUE TITLE
Docker SMTP settings

### ISSUE THREAD

**Issue by ZEROF** [frab/frab#457]
Hi,

Everything seams to work but I have issue setting mail env variables. I created .env.production and I use two methods to run frab container, using docker run or docker-compose up ...all that is cool part, but when i try to reset user password, I get errors.

This is my .env config:

SECRET_KEY_BASE=xxxxxx
FRAB_HOST=xxxxx
FRAB_PROTOCOL=https
FROM_EMAIL=noreplay@xxxxx.org
FRAB_CURRENCY_UNIT="€"
FRAB_CURRENCY_FORMAT="%n%u"
SMTP_ADDRESS=mail.xxxxxx.org
SMTP_PORT=465
SMTP_DOMAIN=xxxxx.org
SMTP_USER_NAME=xxxx@xxxxx.org
SMTP_PASSWORD=xxxxxxx
SMTP_NOTLS=false
DATABASE_URL=sqlite3://localhost/home/frab/production.sqlite3

How I start container:

docker run -it --env-file .env.production -v /data/production.sqlite3:/home/frab/production.sqlite3 -d -p 3000:3000 frab-production

I tested with my mail server and as well with Google smtp, but I'm doing something wrong for sure. Can somebody share working settings for Google smtp or his mail server with SSL/TLS enabled?

I'm not going to post all errors outputs, because i changed env so many times and run container again and again I got all type of errors, but most of the time it was 500 Internal Server Error, saying that auth to my mail server is not working or gmail server as well.

Those are not best error examples but ..

```
I, [2019-02-05T08:15:02.471285 #86]  INFO -- : [3cb16fed-1ebb-4777-907f-58f37f119ba7] Completed 500 Internal Server Error in 60574ms (ActiveRecord: 10.4ms)
F, [2019-02-05T08:15:02.473634 #86] FATAL -- : [3cb16fed-1ebb-4777-907f-58f37f119ba7]   
F, [2019-02-05T08:15:02.473738 #86] FATAL -- : [3cb16fed-1ebb-4777-907f-58f37f119ba7] Net::ReadTimeout (Net::ReadTimeout with #<TCPSocket:(closed)>):
F, [2019-02-05T08:15:02.473815 #86] FATAL -- : [3cb16fed-1ebb-4777-907f-58f37f119ba7]   
F, [2019-02-05T08:15:02.473928 #86] FATAL -- : [3cb16fed-1ebb-4777-907f-58f37f119ba7] /usr/local/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
```

or

```
I, [2019-02-05T08:32:24.390233 #86]  INFO -- : [90d8292b-bcce-4498-8da3-c111ea1e26c3] Completed 500 Internal Server Error in 450ms (ActiveRecord: 14.1ms)
F, [2019-02-05T08:32:24.392592 #86] FATAL -- : [90d8292b-bcce-4498-8da3-c111ea1e26c3]   
F, [2019-02-05T08:32:24.392684 #86] FATAL -- : [90d8292b-bcce-4498-8da3-c111ea1e26c3] SocketError (getaddrinfo: Name or service not known):
F, [2019-02-05T08:32:24.392758 #86] FATAL -- : [90d8292b-bcce-4498-8da3-c111ea1e26c3]   
F, [2019-02-05T08:32:24.392868 #86] FATAL -- : [90d8292b-bcce-4498-8da3-c111ea1e26c3] /usr/local/lib/ruby/2.6.0/net/smtp.rb:539:in `initialize'
```

Etc.. will not troll post with all errors I got :).

I really appreciate any help you can provide. ;)

**Comment by manno** [comment]
This is related to https://github.com/frab/frab/issues/446 and the presence of `SMTP_NOTLS` in the docker file.

**Comment by manno** [comment]
closing this, please reopen if the problem still exists

**Comment by ZEROF** [comment]
Hi @manno,

As i got your answer, i didn't see any change with your fix. Sorry for late update. And i will be back to my original question. Can somebody provide his configuration example (working with docker)? I get same error, with auth option you pushed, it's not working, with notls true or false. Authetication with gmail and our private mail server, same errors go over and over, "Completed 500 Internal Server Error, SocketError (getaddrinfo: Name or service not known)" etc..

**Comment by manno** [comment]
Ah, I see this is a little different. I think `getaddrinfo: Name or service not known` indicates a DNS problem. While ` Net::ReadTimeout` looks like your container has no networking or is firewalled.

Can you `docker exec` into the container and check with ping or netcat if you can access the inernet at all?

**Comment by ZEROF** [comment]
Hi,

Sure, i tested that even before finding issue with mail auth. I just re-tested ping to smtp.gmail.com is working, telnet to our server on port 465 and gmail as well are ok.

Something changed, ERROR

Completed 500 Internal Server Error
EOFError (end of file reached)

.env.production config

    FRAB_HOST=https://****.*
    FRAB_PROTOCOL=https
    FROM_EMAIL=******@****
    FRAB_CURRENCY_UNIT="€"
    FRAB_CURRENCY_FORMAT="%n%u"
    RAILS_SERVE_STATIC_FILES=1
    #EXCEPTION_EMAIL=frab-owner@example.com
    SMTP_ADDRESS=smtp.gmail.com
    SMTP_PORT=465
    SMTP_DOMAIN=https://*****.*
    SMTP_USER_NAME=*@*
    SMTP_PASSWORD=*@*
    #SMTP_AUTHENTICATION=1
    SMTP_NOTLS=true
    DATABASE_URL=sqlite3://********

As you can see i'm using ssl connection to gmail, on port 465 and user/password options.

When I build container I use two ENV variables (this is what I have in my Dockerfile):

     ENV RACK_ENV=production \
        SECRET_KEY_BASE=****************

I have feeling that some variables are not imported to env from .env.production. This is how I run container:

     docker run -it --env-file .env.production  -v /production.sqlite3:/home/frab/production.sqlite3 -h xxxx.x -d -p 3000:3000 frab-production

;)

...

Small update about using gmail. I update https://myaccount.google.com/security settings to get gmail work from container, tested with:

curl smtps://smtp.gmail.com:465 -v --mail-from "xxx@gmail.com" --mail-rcpt "yyy@gmail.com" --ssl -u xxx@gmail.com:password -T "test.txt" -k --anyauth

**Comment by manno** [comment]
I tried the docker image  with a SMTP server and it worked. Not sure what is needed for Gmail, if you goolge `Actionmailer gmail` there are a lot of stackoverflow questions, but apparently people got it to work.

**Comment by ZEROF** [comment]
Using google was for testing only. Can you provide you Docker file but only ENV production settings and .env.production settings as well if you used that. That can help.

Thanks

**Comment by manno** [comment]
I didn't change anything in https://github.com/frab/frab/blob/master/Dockerfile

My `.env.production`:

```
SECRET_KEY_BASE=123
FRAB_HOST=localhost:3000
FRAB_PROTOCOL=http
FROM_EMAIL=manno@example.com
SMTP_ADDRESS=mail.example.com
SMTP_PORT=587
SMTP_NOTLS=false
SMTP_USER_NAME=manno
SMTP_PASSWORD=password
EXCEPTION_EMAIL=manno@example.com
RAILS_SERVE_STATIC_FILES=true
```

**Comment by ZEROF** [comment]
Hi,

Now it's working. Removed SMTP_DOMAIN and other not used settings from .env.production and it's alive with gsuite account settings.

Thanks
