### ISSUE TITLE
Docker README should request persistent storage

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#461]

**Comment by eladeyal-intel** [comment]
you should mount /home/frab/app/public to a persistent storage if you want attachments to be kept. THis should be explicitly described in the README.docker

**Comment by manno** [comment]
Indeed. I also started a branch (https://github.com/frab/frab/tree/active-storage) last year to switch from paperclip to ActiveStorage. I hoped that would make it easier to integrate S3 style storage. However migrating existing installations to the new folder structure for attachments needs more testing.
