### ISSUE TITLE
docker: uid 2000

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#463]
We use frab with cloudfoundry and we mount a CIFS drive for the permsistent mount. It seems that only uid 2000 can have access to the CIFS drive. I've seen uid 2000 as being a popular uid for applications. examples

https://thenewstack.io/cloud-foundry-approach-container-storage-security/

https://github.com/metabase/metabase/blob/a67575a86cc8ab534d67c7c52575df70290b2dda/bin/docker/run_metabase.sh#L32

So I have two proposals

(1) change the uid and gid in the dockerfile to 2000 instead of 1000
(2) change the uid and gid to be controllable by environment variable

**Comment by manno** [comment]
Great to hear you are using frab with cloud foundry. 

Switching the UID could be problematic for existing installations? Anyone out here using it already and have an opinion, @mxmo0rhuhn maybe?

Otherwise let's just wait a few days, switch to 2000 and see if there any complaints...

**Comment by eladeyal-intel** [comment]
@manno ping
