### ISSUE TITLE
conference date logic ignore conference timezone

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#473]
The wording in frab is "Please make sure to submit your proposal until 2019-04-14" and also "The call for participation starts at 2019-01-30 and ends at 2019-04-14." and also "No submission will be possible after this date." My understanding from these expressions is that submission window is open throughout 2019-04-14, and user can still submit on 2019-04-14 23:59 but not on 2019-04-15 00:01.

 **UPDATE** Now I think the problem is that this date does not into account the conference timezone. 

You can test this by setting the conference start & end times to the same date as today (your local time) and change the conference timezone to somewhere where the date is different. You'd want to see the conference submission unavailable, but in fact it's still available.

**Comment by manno** [comment]
The soft limit is not enforced by software. The public wording reflects what is communicated to speakers. Some conferences still allow submissions after that deadline, for different reasons.

**Comment by eladeyal-intel** [comment]
@manno The issue is explicitly about the hard limit

![image](https://user-images.githubusercontent.com/20379005/56413730-15617800-6291-11e9-9e60-d716058b3a46.png)

**Comment by eladeyal-intel** [comment]
I created a CR for this.

So we had two problems. One was that the deadlines were compared to the local time of the server and not to the conference's timezone. 

The other was that this comparison, which would make `still_running?` return `false` on the very last day of the submission window. It should be `true` because the deadline is the "last date for submission"

https://github.com/frab/frab/blob/a688e0195019200d16ca9807c4a95145a032aa9b/app/models/call_for_participation.rb#L16-L18

**Comment by eladeyal-intel** [comment]
#553 merged! closing .
