### ISSUE TITLE
bulk email flow not working w/ integrated ticket sever

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#476]
@manno - this is related to #474

I was trying to understand how things should be working by reading https://github.com/frab/frab/blob/e69a07e537d48eb4c720f3ddc05a665e8fee8c7e/app/views/conferences/_notification_section.html.haml and https://github.com/frab/frab/issues/260

If I understand correctly, if I enable "Bulk notifications enabled" and set "Ticket Server"="Integrated" and I have one event is state "accepting", I should see this text: `1 event in state accepting` followed by a button `Send accepting notifications to 1 speaker in 1 event`

What I see in reality is this:

![image](https://user-images.githubusercontent.com/20379005/56368703-a8060680-6200-11e9-98fa-adbec17d7ce5.png)

I think here https://github.com/frab/frab/blob/e69a07e537d48eb4c720f3ddc05a665e8fee8c7e/app/views/conferences/_notification_section.html.haml#L4 noticket should be set to 0 unless @conference.ticket_server_enabled

thanks

**Comment by manno** [comment]
Sorry, I don't think that this ever worked without a ticket server.
Without a ticket on the event model, how can we make sure only to send emails once to every speaker?

**Comment by eladeyal-intel** [comment]
@manno I thought that it would send the e-mail to all events in "accpeting" state and immediately move them to "accepted" state; So it would not send twice.

**Comment by eladeyal-intel** [comment]
i think this ticket is OK to close
