### ISSUE TITLE
Explain the color coding for the schedule page

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#479]
So I can see that when two events are scheduled in the same time and the same room, then the event is marked red.

I can't understand why sometimes the events are yellow and sometimes they are green?

![image](https://user-images.githubusercontent.com/20379005/56815434-073fc880-684a-11e9-93ce-8defa766ecfd.png)

If I understand correctly, the small box next o the title marks the track.

I think this should be documented in the manual.

**Comment by ScottyTM** [comment]
Green means everything is fine with the talk. Yellow means that there's an issue. Usually it means that the speaker isn't availabe at the time of the talk since they haven't bother to set their availability. You can check by clicking on the talk there should be an info at the top of the page.

**Comment by eladeyal-intel** [comment]
@ScottyTM Thanks

I ended up searching the code https://github.com/frab/frab/search?q=%22Conflict.create%22&unscoped_q=%22Conflict.create%22 and I think this is the color coding. Am I correct?

Fatal (Red) - multiple events in same room concurrently

Warning (Yellow) - same person is speaker in multiple events concurrently

Warning (Yellow) - person has not communicated her availability at the scheduled time

Warning (Yellow) - person is not available at the scheduled time

Green - everything is file.

I propose to add this to the manual. You think its OK?

BTW is there a way to auto-set the availability for all speakers?

**Comment by eladeyal-intel** [comment]
Apparently it was mostly explained in the manual.

I think I clarified things a bit

https://github.com/frab/frab/wiki/Manual/_compare/25f33e28370bc9f6be1ab745865b02689ca43aaf...6c8b9ea46834fa7d1b5c7b7db0613072938b7763

**Comment by manno** [comment]
Thanks!

I don't think we have anything in the frontend yo generate availability. In the Rails console something like this should work:

```
co = Conference.find_by(acronym: 'abc')
Person.speaking_at(co).each { |s| s.create_availabilities_for(co) }
```

**Comment by eladeyal-intel** [comment]
@manno thanks, this seems to work (in the sense that the agenda is now all green for me :-) )

for reference, this is the way I got into the rails console - I run frab from docker in cloudfoundary

```
cf ssh devfrab
PATH=$PATH:/usr/local/bin ~/app/bin/rails console
co = Conference.find_by(acronym: 'XXXXXXXXX')
Person.speaking_at(co).each { |s| s.create_availabilities_for(co) }
```
