### ISSUE TITLE
Manual: events with multiple speakers

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#484]
The manual (wiki) currently state

> A common problem are events with multiple speakers. frab does not allow speakers to add more people to a talk. Neither can they join an existing talk proposal. So, after coordinator and submitter have agreed on the number of speakers, the other speakers sign up with frab and tell their mail addresses to the coordinator. The coordinator can then add them to the talk manually.

But I do see this at the bottom of the event details page:

> Token: b3***********66
> Share this token with speakers you want to allow to join this event. After they have created an account, they can use the token in the 'Join event' interface. This link directly leads to the 'Join event' page for this event.

Is the manual not up to date? Things are confusing

**Comment by manno** [comment]
Yes, the token was added later to make this less painful.

**Comment by eladeyal-intel** [comment]
@manno how about this for the wiki, is it accurate enough?

---

Events with Multiple Speakers

During the call for participation period, the event submitter can invite others to join as speakers to the event. The submitter would open the event details page, scroll to the bottom of the page and find an "invitation token" URL link, which she or he can send to prospective co-speakers. The co-speaker would open that URL link, sign-up to frab, and be added to the event. 

Coordinatos can do the same; and they can also manually add and remove speakers from the event's "Edit People" page, even after the call for participation window is over.

In the past most talks only have one to three speakers for a thirty minute presentation. However, with panel discussions, the coordinator might have to coordinate more than five speakers and a moderator.

**Comment by eladeyal-intel** [comment]
I updated the manual accordingly:

https://github.com/frab/frab/wiki/Manual/_compare/517425126e9fd0fc6fdb329a65cd82b368f9b871...e035d4b9fd450e283d2b0129110cf4990c4ab5e1
