### ISSUE TITLE
Add person: "Assistant"

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#488]
I propose another kind of person to be associated with an event: "Assistant". An Assistant have (read-only?) access to the event they are assigned to. They can see all the info that the submitter see and nothing else. They are not shown in the speaker list or checked for availability.

One use case is that we assign a "mentor" for some events, he or she checks the media attached to the event and can provide feedback.

**Comment by saerdnaer** [comment]
At the conferences I know, this normally the coordinator role...

**Comment by eladeyal-intel** [comment]
@saerdnaer - "coordinator" have more permissions for an event that a submittors; they can accept talks for example. they are part of the conference crew. What we did in our conference is assign mentors which are not conference crew, and they would download the event attachments and comment over it. I want to distinguish them from the event submittors/speakers - for example, don't list them in the schedule; but all communication to the submittors and speakers should be CC to the mentor so she's in the loop.

**Comment by eladeyal-intel** [comment]
![image](https://user-images.githubusercontent.com/20379005/65516697-253d5200-deea-11e9-903d-66aa9c98ddeb.png)

**Comment by eladeyal-intel** [comment]
Merged.

I updated the manual accordingly:

https://github.com/frab/frab/wiki/Manual/_compare/517425126e9fd0fc6fdb329a65cd82b368f9b871...e035d4b9fd450e283d2b0129110cf4990c4ab5e1
