### ISSUE TITLE
Handle events submitted after soft deadline

### ISSUE THREAD

**Issue by towo** [frab/frab#490]
1. There should be some kind of indication that an event was submitted after the soft deadline for an event.
2. The review mode should also have a toggle for only showing in-deadline events.

**Comment by towo** [comment]
I might just implement this myself, would be good practice.

**Comment by manno** [comment]
You could add the `created_at` date to the event view

**Comment by eladeyal-intel** [comment]
@towo you can add `created_at` and add a sentence `(after soft dead-line)` in orange and even `(after the submission dead-line)` in red.

**Comment by eladeyal-intel** [comment]
@towo merged in #626. I propose to close this ticket.

**Comment by towo** [comment]
Agreed, @eladeyal-intel.
