### ISSUE TITLE
Attachments file size is hard limited

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#493]
Attachments file size is hard limited to 42MB.

https://github.com/frab/frab/blob/cbe681c60e8f5734acf10f116a8d8acefebd2498/app/models/event_attachment.rb#L6

@manno is there a reason to this specific limit? (i.e. something bad will happen if we try to store larger files)

Can we make this configurable?

**Comment by eladeyal-intel** [comment]
@manno ? anyone?

**Comment by manno** [comment]
@eladeyal-intel  I think that limit is arbitrary, feel free to make it configurable. Paperclip may upload to memory first, that might be a limiting factor.

**Comment by eladeyal-intel** [comment]
Thanks. I tried to change it to 420MB https://github.com/eladeyal-intel/frab/commit/8e95bfeb65544f572307138b4484b2af589def52 and it seems to work OK. I don't know how you make such a thing configurable myself.
