### ISSUE TITLE
German translation of "Remove person" broken

### ISSUE THREAD

**Issue by vollkorn1982** [frab/frab#494]
When using frab in German and clicking on the "Benutzerdefinierte Benachrichtigung" button of  an event, the buttons to remove the persons are labeled like this:

{:one=>"Person", :other=>"Personen"} entfernen

I would expect them to be labeled "Person entfernen" or "Personen entfernen" instead.

**Comment by eladeyal-intel** [comment]
![image](https://user-images.githubusercontent.com/20379005/64595131-00a98c00-d3ba-11e9-9c84-9f136f6c5c9c.png)

**Comment by eladeyal-intel** [comment]
If you change `de.yml`

instead of
```
      event_person:
        one: Person
        other: Personen
```
to be
```
     event_person: Person
```

this specific artifact goes away. The `activerecord.models` section seem to be singular only for all the languages I checked.

**Comment by cyroxx** [comment]
Since #551 was merged, this can probably be closed?

**Comment by erdgeist** [comment]
Yep. Just checked that it looks okay. There was only one person to remove, anyway.
