### ISSUE TITLE
NoMethodError in Conferences#update

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#506]
trying to add a notification but there are no events yet

![image](https://user-images.githubusercontent.com/20379005/63496096-ecb0ef80-c4c9-11e9-8389-df4589365941.png)

**Comment by manno** [comment]
if `@accepting&.count` would be the fix here

**Comment by eladeyal-intel** [comment]
I may have been to quick to open the issue. I am unable to reproduce. Close with no action?
