### ISSUE TITLE
Add count (and sub-count) to index views

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#577]
It would be cool to have a quick overview about the number of Events and Persons in their respective Lists, something along the lines of

<h1>Listing 999 events</h1>

and for Filtered Views

<h1>Listing 123/999 events</h1>

After looking into the code, I don't find an obvious place to get both values to the template. Any idea?

**Comment by eladeyal-intel** [comment]
@erdgeist See #570 I started this. I think you can see my code there. Does this make sense ?

**Comment by erdgeist** [comment]
That's good. Can you please create a PR out of this commit? I can't find a way to do that from the interface.

**Comment by eladeyal-intel** [comment]
@erdgeist I think it's time to close this ticket.

**Comment by eladeyal-intel** [comment]
Still fixed. Still needs to be closed.
