### ISSUE TITLE
Event list exceeds container

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#589]
Somehow the new list style doesn't quite fit the view:

![Screenshot 2019-10-10 at 19 09 56](https://user-images.githubusercontent.com/59463/66590850-f71a6c00-eb91-11e9-8d0e-a88cba7d0334.png)

No clue where to look for it.

**Comment by eladeyal-intel** [comment]
It only happens in the "All persons" list, where there are 4 buttons to the right of the names and not 3 like the other tabs.

**Comment by eladeyal-intel** [comment]
@erdgeist here's my first attempt to look at it. (I used Google Chrome Developer pane as a "where to look for") - https://github.com/eladeyal-intel/frab/commit/ed785934c09b7db975528256612be1365cffe922

So this seems to enlarge the white container in to the fit the content. But oddly it is not horizontally centralized.

![image](https://user-images.githubusercontent.com/20379005/66648546-71033180-ec34-11e9-9fd6-a76175be06a9.png)

**Comment by erdgeist** [comment]
Thanks.

I am not a big fan of monkey patching vendor CSS, since those changes tend to get lost when syncing with upstream. Can we put this all into frab.css?

**Comment by eladeyal-intel** [comment]
@erdgeist see now?

**Comment by erdgeist** [comment]
Fixed by #599
