### ISSUE TITLE
Confusing link in admin CfP page

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#602]
When the admin looks at the CfP page, a link to the CFP is provided.

For some reason not clear to me, (I suspect a bug), two URLs are presented.

To further the confusion, while 2 different URLs are presented, the click targets are actually the same.

![image](https://user-images.githubusercontent.com/20379005/67161666-58e28f00-f365-11e9-939a-39be233caba9.png)

The last modification to this code is here: https://github.com/frab/frab/commit/18e89507872e4fa34bb6ee40b308425857041d41#diff-1ab41d9b78fbf906469a9cd8d4a975a1 

The code is here
https://github.com/frab/frab/blob/6b462664f93712c5a2f46ab73ee8f8ec783125c7/app/views/call_for_participations/show.html.haml#L11-L13

So why are there two links? or: Which is the correct link?

thanks

**Comment by erdgeist** [comment]
I think only the cfp_root_url should be presented.
