### ISSUE TITLE
Highlight submissions from after soft deadline

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#619]
Currently the only way to identify late submissions is to look at their creation date in list views. Those dates even seem to not be properly aligned with the UTC based end of CfP phase. So the only way for me to tell them was to compare event ids by the first known late submission.

It would be cool if the submission date/time could be more visible in review or edit views and/or if late submissions could get a badge or other visual hint that aids reviewers.

**Comment by eladeyal-intel** [comment]
1. We just merged that the CfP ends not in UTC midnight but in the midnight of the conference timezone.

2. I think there's some confusion with the TZ of different time items presented.

3. duplicate of #490

**Comment by erdgeist** [comment]
Right. Closing this as a dupe.
