### ISSUE TITLE
Sort event list by creation date does not work

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#632]
When clicking the 'Created by' header, the browser is directed to 

`https://devfrab.app.intel.com/en/ilcc2019/events?events=my&q%5Bs%5D=Created+desc`

but it should go to

`https://devfrab.app.intel.com/en/ilcc2019/events?events=my&q%5Bs%5D=created_by+desc`

**Comment by erdgeist** [comment]
I think it should point to "created_at" and not "created_by" and I think I have fixed it in #633.

**Comment by erdgeist** [comment]
Fixed in #633
