### ISSUE TITLE
CI Tests sometimes fail in filter_and_send_mail_test

### ISSUE THREAD

**Issue by erdgeist** [frab/frab#634]
E
983
984Error:
985FilterAndSendMailTest#test_0001_can create a template and use it for filter and send:
986Capybara::ElementNotFound: Unable to find visible field "Name" that is not disabled
987    test/features/filter_and_send_mail_test.rb:16:in `block in <class:FilterAndSendMailTest>'
988
989bin/rails test test/features/filter_and_send_mail_test.rb:11
990
991

@eladeyal-intel Any  idea, why that is? Master is marked broken because this test failed in one of six instances.

**Comment by eladeyal-intel** [comment]
I haven't seen that in a while. I propose to close this issue.

See #691 though.
