### ISSUE TITLE
QR Code broken

### ISSUE THREAD

**Issue by codingHahn** [frab/frab#679]
In the current Fahrplan of the 36c3 the qr-code is broken. It is because the cells in the qr code have a margin set. Removing that margin fixes the qr code.

![broken](https://user-images.githubusercontent.com/16626332/71122696-7c994880-21e1-11ea-926a-2a5116c936ac.png)
![fixed](https://user-images.githubusercontent.com/16626332/71122736-8e7aeb80-21e1-11ea-90f3-ed7db7f78cf5.png)

**Comment by erdgeist** [comment]
This is not an issue with frab but with the custom CSS we're using for 36C3.

Closing it.
