### ISSUE TITLE
Feature: allow translation of talk titles and abstracts

### ISSUE THREAD

**Issue by stblassitude** [frab/frab#682]
Especially for C3, there are a large number of attendees who would benefit from having the talk titles and at least the first paragraph of the abstract translated into English or German, respectively. Since for C3, all talks are always translated into English or German, this would help people pick relevant talks.

I don't think a full-blown multi-language model would be needed.

If a translation team could help with creating and maintaining the translations, that would be even better.

**Comment by manno** [comment]
PR #872 adds translated input boxes to the orga's edit forms, the static schedule export and the speaker.json, schedule.json endpoints. It's not added to the cfp forms, or the orga's "show event" screens.
