### ISSUE TITLE
Is anyone interested in reviewing the multiple PRs waiting?

### ISSUE THREAD

**Issue by eladeyal-intel** [frab/frab#714]
https://github.com/frab/frab/pulls

**Comment by eladeyal-intel** [comment]
@manno @erdgeist 
I hope these strangest of times find you well enough. Maybe you'd lol to review my PRs, some are 7mo old...

Cheers

**Comment by erdgeist** [comment]
Sorry about that. Will take a look this week. Thanks for your patience.

**Comment by eladeyal-intel** [comment]
@erdgeist thank you for your help

**Comment by eladeyal-intel** [comment]
@erdgeist @manno Would you like to review some pending PRs?

**Comment by eladeyal-intel** [comment]
@manno thanks for reviewing some of the PRs. I went ahead and re-based the remaining relevant PRs. Thanks

**Comment by eladeyal-intel** [comment]
@manno  / @erdgeist  maybe you want to continue reviewing and merging the open PRs?

**Comment by saerdnaer** [comment]
It looks like I would have the rights to do it, but am not really sure about the process...

**Comment by saerdnaer** [comment]
@eladeyal-intel I think you should now have write requests to this repo, you can merge PRs to master – if they have at least one approving review from another user.

**Comment by eladeyal-intel** [comment]
Thanks alot @saerdnaer . I will merge stuff.

**Comment by eladeyal-intel** [comment]
done
