### ISSUE TITLE
Generate a starting/closing slide for each event

### ISSUE THREAD

**Issue by wvholst** [frab/frab#90]
Have FRAB generate a starting and a closing slide for each event that:

- displays the license
- displays the conference logo
- displays the changes in the programme for that day that are still relevant at that point in time
- allows for announcements (pick your trash/we need more volunteers/the water is potable/use sunscreen etc.)
- displays a feedback URL per event and/or QR code

**Comment by saerdnaer** [comment]
We normally use other software to do such things, like https://info-beamer.com/pi during the event  and http://github.com/voc/intro-outro-generator/ for the final recordings.

**Comment by MaZderMind** [comment]
I'd really not want to see Image-Generation or even Video-Generation with Artwork and Animations and all that stuff inside a planning tool.

**Comment by wvholst** [comment]
The request does not necessarily require image generation or video generation. It is a pain when you have last-minute changes to have to re-enter the data manually into other tools. So the ability to invoke other tools based on templates (like for mail) would suffice.

**Comment by jjeising** [comment]
For external updates all existing tools use the Fahrplan XML export. When changes occur you can add a new export version. Our existing tools import this data or simply replace the XML file as data source.
