### ISSUE TITLE
Make "Person"-Selection better by implementing JS-based name selection

### ISSUE THREAD

**Issue by Unicorn-rzl** [frab/frab#93]
With larger and older frab installations, the amount of accounts gets bigger and bigger. To make things worse, the current way to add a person to an event is to select the name from a drop-down containing every account in the system.

My suggestion would be to use a textfield where one could enter a name (or part of a name) and the interface returns a list of names/accounts containing the string. Even better would be a AJAX-like approach with search-as-you-type.

**Comment by catcosmo** [comment]
that would be very helpful indeed.

**Comment by erdgeist** [comment]
Take a look at #214, looks like it exactly does what you need.
